// web/src/features/dashboard/ScopeSidebar.tsx
import { useState, type FormEvent, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import type { GithubEnvironment } from '../../api/types'
import type { LedgerFilters } from '../ledger/FilterBar'

interface ScopeSidebarProps {
  org: string
  repo?: string
  environments: GithubEnvironment[]
  showOrgLevel: boolean
  filters: LedgerFilters
  onNavigate: (level: LedgerFilters['level'], env?: string) => void
  onCreateEnvironment: (name: string) => Promise<void>
  onDeleteEnvironment: (name: string) => void
}

export function ScopeSidebar({
  org,
  repo,
  environments,
  showOrgLevel,
  filters,
  onNavigate,
  onCreateEnvironment,
  onDeleteEnvironment,
}: ScopeSidebarProps) {
  return (
    <nav aria-label="Scope" className="space-y-0.5">
      <p className="mb-2 px-2 font-mono text-[11px] uppercase tracking-wider text-text-dim">Scope</p>

      <TreeItem active={filters.level === 'all'} label="Everything" onClick={() => onNavigate('all')} />

      {showOrgLevel ? (
        <TreeItem
          active={filters.level === 'organization'}
          label="Organization"
          meta={org}
          icon={<OrgIcon />}
          onClick={() => onNavigate('organization')}
        />
      ) : null}

      {repo ? (
        <>
          <TreeItem
            active={filters.level === 'repository'}
            label="Repository"
            meta={repo}
            icon={<RepoIcon />}
            onClick={() => onNavigate('repository')}
          />
          <div className="ml-4 space-y-0.5 border-l border-line pl-3">
            {environments.map((env) => (
              <EnvironmentItem
                key={env.id}
                active={filters.level === 'environment' && filters.env === env.name}
                label={env.name}
                onClick={() => onNavigate('environment', env.name)}
                onDelete={() => onDeleteEnvironment(env.name)}
              />
            ))}
            <NewEnvironmentForm onCreate={onCreateEnvironment} />
          </div>
        </>
      ) : null}

      <div className="pt-3">
        <Link
          to="/"
          className="flex items-center gap-2 rounded-md px-2 py-1.5 text-xs text-text-dim hover:bg-panel-raised hover:text-text"
        >
          <SwitchIcon />
          Switch scope
        </Link>
      </div>
    </nav>
  )
}

function TreeItem({
  active,
  label,
  meta,
  icon,
  onClick,
}: {
  active: boolean
  label: string
  meta?: string
  icon?: ReactNode
  onClick: () => void
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-current={active ? 'true' : undefined}
      className={`flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm transition-colors ${
        active ? 'bg-brand-dim font-medium text-brand' : 'text-text-dim hover:bg-panel-raised hover:text-text'
      }`}
    >
      {icon ? <span className="shrink-0 opacity-80">{icon}</span> : null}
      <span className="min-w-0 flex-1 truncate">
        {label}
        {meta ? <span className="ml-1 truncate opacity-70">&middot; {meta}</span> : null}
      </span>
    </button>
  )
}

function EnvironmentItem({
  active,
  label,
  onClick,
  onDelete,
}: {
  active: boolean
  label: string
  onClick: () => void
  onDelete: () => void
}) {
  return (
    <div
      className={`group flex items-center rounded-md transition-colors ${
        active ? 'bg-brand-dim' : 'hover:bg-panel-raised'
      }`}
    >
      <button
        type="button"
        onClick={onClick}
        aria-current={active ? 'true' : undefined}
        className={`flex min-w-0 flex-1 items-center gap-2 px-2 py-1.5 text-left text-sm ${
          active ? 'font-medium text-brand' : 'text-text-dim group-hover:text-text'
        }`}
      >
        <span className="shrink-0 opacity-80">
          <EnvIcon />
        </span>
        <span className="min-w-0 flex-1 truncate">{label}</span>
      </button>
      <button
        type="button"
        onClick={onDelete}
        title={`Delete environment "${label}"`}
        className="mr-1 shrink-0 rounded p-1 text-text-dim opacity-0 hover:text-danger group-hover:opacity-100"
      >
        <TrashIcon />
      </button>
    </div>
  )
}

function NewEnvironmentForm({ onCreate }: { onCreate: (name: string) => Promise<void> }) {
  const [open, setOpen] = useState(false)
  const [name, setName] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  function close() {
    setOpen(false)
    setName('')
    setError(null)
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    if (!name.trim()) return
    setSubmitting(true)
    setError(null)
    try {
      await onCreate(name.trim())
      close()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'GitHub rejected this request.')
    } finally {
      setSubmitting(false)
    }
  }

  if (!open) {
    return (
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm text-text-dim hover:bg-panel-raised hover:text-text"
      >
        <PlusIcon />
        New environment
      </button>
    )
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-1.5 px-1 py-1">
      <input
        autoFocus
        value={name}
        onChange={(e) => setName(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === 'Escape') close()
        }}
        placeholder="production"
        spellCheck={false}
        className="w-full rounded-md border border-line bg-ink px-2 py-1 font-mono text-xs text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none"
      />
      {error ? <p className="text-xs text-danger">{error}</p> : null}
      <div className="flex gap-1.5">
        <button
          type="submit"
          disabled={submitting || !name.trim()}
          className="rounded-md bg-brand px-2 py-1 text-xs font-medium text-on-brand disabled:opacity-40"
        >
          {submitting ? 'Creating…' : 'Create'}
        </button>
        <button
          type="button"
          onClick={close}
          className="rounded-md px-2 py-1 text-xs text-text-dim hover:text-text"
        >
          Cancel
        </button>
      </div>
    </form>
  )
}

function OrgIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <rect x="3" y="3" width="7" height="7" rx="1" />
      <rect x="14" y="3" width="7" height="7" rx="1" />
      <rect x="3" y="14" width="7" height="7" rx="1" />
      <rect x="14" y="14" width="7" height="7" rx="1" />
    </svg>
  )
}

function RepoIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" />
      <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z" />
    </svg>
  )
}

function EnvIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="m12 2 9 4.9v10.2L12 22l-9-4.9V6.9L12 2Z" />
      <path d="M12 22v-9.1M3 6.9l9 5 9-5" />
    </svg>
  )
}

function SwitchIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="M7 16V4M7 4 3 8M7 4l4 4" />
      <path d="M17 8v12M17 20l4-4M17 20l-4-4" />
    </svg>
  )
}

function PlusIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="M12 5v14M5 12h14" />
    </svg>
  )
}

function TrashIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="M3 6h18" />
      <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2m3 0-1 14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2L4 6" />
    </svg>
  )
}

// client/src/app/features/dashboard/ScopeSidebar.component.ts
import { Component, ElementRef, Injector, ViewChild, afterNextRender, inject, input, output, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { EnvironmentsFacade } from '../../core/facades/EnvironmentsFacade';
import type { GithubEnvironment } from '../../core/Types';
import type { LedgerFilters } from '../ledger/LedgerFilters';

export interface ScopeNavigateEvent {
  level: LedgerFilters['level'];
  env?: string;
}

/**
 * Port of web/src/features/dashboard/ScopeSidebar.tsx. `onNavigate`/`onRenameEnvironment`/
 * `onDeleteEnvironment` stay callback-shaped (outputs) — DashboardShellComponent owns what
 * happens next (updating filters, opening a dialog). `onCreateEnvironment` doesn't: the original
 * is `(name: string) => Promise<void>`, awaited directly by the form so it can show its own
 * error and reset itself — an Angular `output()` can't hand a promise back to its emitter, so
 * this component injects EnvironmentsFacade directly and drives that flow itself instead of
 * routing it through the parent.
 */
@Component({
  selector: 'app-scope-sidebar',
  imports: [RouterLink],
  templateUrl: './ScopeSidebar.component.html',
})
export class ScopeSidebarComponent {
  readonly org = input.required<string>();
  readonly repo = input<string | undefined>(undefined);
  readonly environments = input<GithubEnvironment[]>([]);
  readonly showOrgLevel = input(false);
  readonly filters = input.required<LedgerFilters>();

  readonly navigate = output<ScopeNavigateEvent>();
  readonly renameEnvironment = output<string>();
  readonly deleteEnvironment = output<string>();

  private readonly environmentsFacade = inject(EnvironmentsFacade);
  private readonly injector = inject(Injector);

  protected readonly newEnvOpen = signal(false);
  protected readonly newEnvName = signal('');
  protected readonly newEnvError = signal<string | null>(null);
  protected readonly newEnvSubmitting = signal(false);

  // The field only exists in the DOM once newEnvOpen() is true, so — unlike ScopePickerComponent's
  // always-present search input — this can't just focus once in ngAfterViewInit. Focused
  // programmatically (not via the `autofocus` attribute — see ScopePickerComponent's doc comment)
  // right after the form's next render each time it opens.
  @ViewChild('newEnvInput') private readonly newEnvInput?: ElementRef<HTMLInputElement>;

  protected TreeItemClasses(active: boolean): string {
    return `flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm transition-colors ${
      active ? 'bg-brand-dim font-medium text-brand' : 'text-text-dim hover:bg-panel-raised hover:text-text'
    }`;
  }

  protected EnvironmentRowClasses(active: boolean): string {
    return `group flex items-center rounded-md transition-colors ${active ? 'bg-brand-dim' : 'hover:bg-panel-raised'}`;
  }

  protected EnvironmentLabelClasses(active: boolean): string {
    return `flex min-w-0 flex-1 items-center gap-2 px-2 py-1.5 text-left text-sm ${
      active ? 'font-medium text-brand' : 'text-text-dim group-hover:text-text'
    }`;
  }

  protected OpenNewEnvForm(): void {
    this.newEnvOpen.set(true);
    afterNextRender(() => this.newEnvInput?.nativeElement.focus(), { injector: this.injector });
  }

  protected CloseNewEnvForm(): void {
    this.newEnvOpen.set(false);
    this.newEnvName.set('');
    this.newEnvError.set(null);
  }

  protected HandleNewEnvNameInput(event: Event): void {
    this.newEnvName.set((event.target as HTMLInputElement).value);
  }

  protected HandleNewEnvKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') this.CloseNewEnvForm();
  }

  protected async HandleCreateEnvironment(event: Event): Promise<void> {
    event.preventDefault();
    const name = this.newEnvName().trim();
    const repo = this.repo();
    if (!name || !repo) return;

    this.newEnvSubmitting.set(true);
    this.newEnvError.set(null);
    try {
      await this.environmentsFacade.createEnvironment.mutateAsync({ org: this.org(), repo, name });
      this.CloseNewEnvForm();
    } catch (err) {
      this.newEnvError.set(err instanceof Error ? err.message : 'GitHub rejected this request.');
    } finally {
      this.newEnvSubmitting.set(false);
    }
  }
}

<nav aria-label="Scope" class="space-y-0.5">
  <p class="mb-2 px-2 font-mono text-[11px] uppercase tracking-wider text-text-dim">Scope</p>

  <button
    type="button"
    [class]="TreeItemClasses(filters().level === 'all')"
    [attr.aria-current]="filters().level === 'all' ? 'true' : null"
    (click)="navigate.emit({ level: 'all' })"
  >
    <span class="min-w-0 flex-1 truncate">Everything</span>
  </button>

  @if (showOrgLevel()) {
    <button
      type="button"
      [class]="TreeItemClasses(filters().level === 'organization')"
      [attr.aria-current]="filters().level === 'organization' ? 'true' : null"
      (click)="navigate.emit({ level: 'organization' })"
    >
      <span class="shrink-0 opacity-80">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
          <rect x="3" y="3" width="7" height="7" rx="1" />
          <rect x="14" y="3" width="7" height="7" rx="1" />
          <rect x="3" y="14" width="7" height="7" rx="1" />
          <rect x="14" y="14" width="7" height="7" rx="1" />
        </svg>
      </span>
      <span class="min-w-0 flex-1 truncate">Organization<span class="ml-1 truncate opacity-70">&middot; {{ org() }}</span></span>
    </button>
  }

  @if (repo(); as repoName) {
    <button
      type="button"
      [class]="TreeItemClasses(filters().level === 'repository')"
      [attr.aria-current]="filters().level === 'repository' ? 'true' : null"
      (click)="navigate.emit({ level: 'repository' })"
    >
      <span class="shrink-0 opacity-80">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
          <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" />
          <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z" />
        </svg>
      </span>
      <span class="min-w-0 flex-1 truncate">Repository<span class="ml-1 truncate opacity-70">&middot; {{ repoName }}</span></span>
    </button>

    <div class="ml-4 space-y-0.5 border-l border-line pl-3">
      @for (env of environments(); track env.id) {
        <div [class]="EnvironmentRowClasses(filters().level === 'environment' && filters().env === env.name)">
          <button
            type="button"
            [class]="EnvironmentLabelClasses(filters().level === 'environment' && filters().env === env.name)"
            [attr.aria-current]="filters().level === 'environment' && filters().env === env.name ? 'true' : null"
            (click)="navigate.emit({ level: 'environment', env: env.name })"
          >
            <span class="shrink-0 opacity-80">
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                <path d="m12 2 9 4.9v10.2L12 22l-9-4.9V6.9L12 2Z" />
                <path d="M12 22v-9.1M3 6.9l9 5 9-5" />
              </svg>
            </span>
            <span class="min-w-0 flex-1 truncate">{{ env.name }}</span>
          </button>
          <button
            type="button"
            (click)="renameEnvironment.emit(env.name)"
            title='Rename environment "{{ env.name }}"'
            class="shrink-0 rounded p-1 text-text-dim opacity-0 hover:text-text group-hover:opacity-100"
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
              <path d="M12 20h9" />
              <path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5Z" />
            </svg>
          </button>
          <button
            type="button"
            (click)="deleteEnvironment.emit(env.name)"
            title='Delete environment "{{ env.name }}"'
            class="mr-1 shrink-0 rounded p-1 text-text-dim opacity-0 hover:text-danger group-hover:opacity-100"
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
              <path d="M3 6h18" />
              <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2m3 0-1 14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2L4 6" />
            </svg>
          </button>
        </div>
      }

      @if (!newEnvOpen()) {
        <button
          type="button"
          (click)="OpenNewEnvForm()"
          class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm text-text-dim hover:bg-panel-raised hover:text-text"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
            <path d="M12 5v14M5 12h14" />
          </svg>
          New environment
        </button>
      } @else {
        <form (submit)="HandleCreateEnvironment($event)" class="space-y-1.5 px-1 py-1">
          <input
            #newEnvInput
            [value]="newEnvName()"
            (input)="HandleNewEnvNameInput($event)"
            (keydown)="HandleNewEnvKeydown($event)"
            placeholder="production"
            spellcheck="false"
            class="w-full rounded-md border border-line bg-ink px-2 py-1 font-mono text-xs text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none"
          />
          @if (newEnvError()) {
            <p class="text-xs text-danger">{{ newEnvError() }}</p>
          }
          <div class="flex gap-1.5">
            <button
              type="submit"
              [disabled]="newEnvSubmitting() || !newEnvName().trim()"
              class="rounded-md bg-brand px-2 py-1 text-xs font-medium text-on-brand disabled:opacity-40"
            >
              {{ newEnvSubmitting() ? 'Creating…' : 'Create' }}
            </button>
            <button type="button" (click)="CloseNewEnvForm()" class="rounded-md px-2 py-1 text-xs text-text-dim hover:text-text">
              Cancel
            </button>
          </div>
        </form>
      }
    </div>
  }

  <div class="pt-3">
    <a
      routerLink="/"
      class="flex items-center gap-2 rounded-md px-2 py-1.5 text-xs text-text-dim hover:bg-panel-raised hover:text-text"
    >
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
        <path d="M7 16V4M7 4 3 8M7 4l4 4" />
        <path d="M17 8v12M17 20l4-4M17 20l-4-4" />
      </svg>
      Switch scope
    </a>
  </div>
</nav>
