// web/src/features/item-editor/ItemEditorPanel.tsx
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { useAuth } from '../../auth/AuthContext'
import {
  useCreateVariable,
  useOrgRepos,
  usePutSecret,
  useRenameSecret,
  useUpdateVariable,
  type DashboardScope,
} from '../../api/hooks'
import type { GithubEnvironment, ItemKind, ItemLevel, LedgerItem, ScopeRef, SecretVisibility } from '../../api/types'
import type { PutSecretOptions } from '../../api/secrets'
import { Button } from '../../components/Button'

interface ItemEditorPanelProps {
  scope: DashboardScope
  environments: GithubEnvironment[]
  initial: LedgerItem | null
  /** Pre-fill the level/environment when opened from a section's own "+ Add" button. */
  initialLevel?: ItemLevel
  initialEnv?: string
  showOrgLevel: boolean
  onClose: () => void
}

const NAME_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/

export function ItemEditorPanel({
  scope,
  environments,
  initial,
  initialLevel,
  initialEnv,
  showOrgLevel,
  onClose,
}: ItemEditorPanelProps) {
  const isEdit = !!initial
  const { token } = useAuth()

  const [level, setLevel] = useState<ItemLevel>(
    initial?.level ?? initialLevel ?? (scope.repo ? 'repository' : 'organization'),
  )
  const [envName, setEnvName] = useState<string>(
    initial?.scope.env ?? initialEnv ?? environments[0]?.name ?? '',
  )
  const [kind, setKind] = useState<ItemKind>(initial?.kind ?? 'variable')
  const [name, setName] = useState(initial?.name ?? '')
  const [value, setValue] = useState(initial?.kind === 'variable' ? (initial.value ?? '') : '')
  const [visibility, setVisibility] = useState<SecretVisibility>(initial?.visibility ?? 'all')
  const [selectedRepoIds, setSelectedRepoIds] = useState<Set<number>>(new Set())
  const [error, setError] = useState<string | null>(null)

  const createVariable = useCreateVariable(token)
  const updateVariable = useUpdateVariable(token)
  const putSecret = usePutSecret(token)
  const renameSecret = useRenameSecret(token)
  const submitting =
    createVariable.isPending || updateVariable.isPending || putSecret.isPending || renameSecret.isPending

  const needsVisibilityPicker = kind === 'secret' && level === 'organization'
  const orgReposQuery = useOrgRepos(token, scope.org, needsVisibilityPicker && visibility === 'selected')

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [onClose])

  const nameValid = name.length === 0 || NAME_PATTERN.test(name)

  const targetScope = useMemo<ScopeRef>(() => {
    if (level === 'organization') return { org: scope.org }
    if (level === 'repository') return { org: scope.org, repo: scope.repo }
    return { org: scope.org, repo: scope.repo, env: envName }
  }, [level, scope, envName])

  const isRenaming = isEdit && name !== initial!.name

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    setError(null)

    if (!name.trim() || !NAME_PATTERN.test(name)) {
      setError('Name must start with a letter or underscore and contain only letters, numbers, and underscores.')
      return
    }
    if (level === 'environment' && !envName) {
      setError('Choose an environment.')
      return
    }
    if (kind === 'variable' && !value.trim()) {
      setError('Enter a value for this variable.')
      return
    }
    if (kind === 'secret' && (!isEdit || isRenaming) && !value) {
      setError(
        isRenaming
          ? 'Enter a value — GitHub can’t copy a secret’s value when renaming it, so you’ll need to re-enter it under the new name.'
          : 'Enter a value for this secret.',
      )
      return
    }

    try {
      if (kind === 'variable') {
        if (isEdit) {
          await updateVariable.mutateAsync({ scope: targetScope, level, currentName: initial!.name, newName: name, value })
        } else {
          await createVariable.mutateAsync({ scope: targetScope, level, name, value })
        }
      } else {
        const options: PutSecretOptions | undefined =
          level === 'organization' ? { visibility, selectedRepositoryIds: [...selectedRepoIds] } : undefined

        if (isEdit && isRenaming) {
          await renameSecret.mutateAsync({ scope: targetScope, level, currentName: initial!.name, newName: name, value, options })
        } else if (isEdit && !value) {
          onClose()
          return
        } else {
          await putSecret.mutateAsync({ scope: targetScope, level, name, value, options })
        }
      }
      onClose()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'GitHub rejected this request.')
    }
  }

  function toggleRepo(id: number) {
    setSelectedRepoIds((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  return (
    <div className="fixed inset-0 z-40 flex justify-end bg-black/40 backdrop-blur-[2px]" role="presentation" onClick={onClose}>
      <form
        onSubmit={handleSubmit}
        onClick={(e) => e.stopPropagation()}
        className="flex h-full w-full max-w-md flex-col overflow-y-auto border-l border-line bg-panel shadow-2xl shadow-black/10"
      >
        <div className="border-b border-line px-5 py-4">
          <p className="font-mono text-xs uppercase tracking-widest text-brand">{isEdit ? 'Edit' : 'Add'}</p>
          <h2 className="mt-1 font-display text-lg font-semibold text-text">
            {isEdit ? initial!.name : 'New variable or secret'}
          </h2>
        </div>

        <div className="flex-1 space-y-4 px-5 py-4">
          <Field label="Level">
            {scope.repo && !isEdit ? (
              <select
                className={selectClass}
                value={level}
                onChange={(e) => setLevel(e.target.value as ItemLevel)}
              >
                {showOrgLevel && <option value="organization">Organization ({scope.org})</option>}
                <option value="repository">Repository ({scope.repo})</option>
                {environments.length > 0 && <option value="environment">Environment</option>}
              </select>
            ) : (
              <p className="font-mono text-sm text-text-dim">
                {level}
                {level === 'environment' ? `: ${envName}` : ''}
              </p>
            )}
          </Field>

          {!isEdit && level === 'environment' ? (
            <Field label="Environment">
              <select className={selectClass} value={envName} onChange={(e) => setEnvName(e.target.value)}>
                {environments.map((env) => (
                  <option key={env.id} value={env.name}>
                    {env.name}
                  </option>
                ))}
              </select>
            </Field>
          ) : null}

          <Field label="Type">
            {isEdit ? (
              <p className="font-mono text-sm text-text-dim">{kind}</p>
            ) : (
              <div className="flex gap-2">
                <KindOption
                  label="Variable"
                  tone="variable"
                  active={kind === 'variable'}
                  onClick={() => setKind('variable')}
                />
                <KindOption
                  label="Secret"
                  tone="secret"
                  active={kind === 'secret'}
                  onClick={() => setKind('secret')}
                />
              </div>
            )}
          </Field>

          <Field label="Name">
            <input
              autoFocus={!isEdit}
              value={name}
              onChange={(e) => setName(e.target.value.toUpperCase())}
              placeholder="API_URL"
              spellCheck={false}
              className={inputClass}
            />
            {!nameValid ? (
              <p className="mt-1 text-xs text-danger">Letters, numbers, and underscores only.</p>
            ) : null}
            {isRenaming && kind === 'secret' ? (
              <p className="mt-1 text-xs text-text-dim">
                Secrets can&rsquo;t be renamed directly — this creates{' '}
                <span className="font-mono text-secret">{name || '…'}</span> with the value below, then deletes{' '}
                <span className="font-mono">{initial!.name}</span>.
              </p>
            ) : null}
          </Field>

          <Field label={kind === 'secret' ? 'Value (write-only — GitHub will never show it again)' : 'Value'}>
            <textarea
              autoFocus={isEdit}
              rows={3}
              value={value}
              onChange={(e) => setValue(e.target.value)}
              placeholder={isEdit && kind === 'secret' ? 'Enter a new value to replace the current one' : ''}
              spellCheck={false}
              className={`${inputClass} resize-y`}
            />
          </Field>

          {needsVisibilityPicker ? (
            <Field label="Which repos can use this?">
              <select
                className={selectClass}
                value={visibility}
                onChange={(e) => setVisibility(e.target.value as SecretVisibility)}
              >
                <option value="all">All repositories</option>
                <option value="private">Private repositories</option>
                <option value="selected">Selected repositories</option>
              </select>
              {visibility === 'selected' ? (
                <div className="mt-2 max-h-40 overflow-y-auto rounded-md border border-line">
                  {orgReposQuery.isLoading ? (
                    <p className="p-3 text-xs text-text-dim">Loading repositories&hellip;</p>
                  ) : (
                    (orgReposQuery.data ?? []).map((repo) => (
                      <label
                        key={repo.id}
                        className="flex items-center gap-2 border-b border-line px-3 py-1.5 text-sm text-text last:border-b-0"
                      >
                        <input
                          type="checkbox"
                          checked={selectedRepoIds.has(repo.id)}
                          onChange={() => toggleRepo(repo.id)}
                        />
                        <span className="font-mono text-xs">{repo.name}</span>
                      </label>
                    ))
                  )}
                </div>
              ) : null}
            </Field>
          ) : null}

          {error ? <p className="text-sm text-danger">{error}</p> : null}
        </div>

        <div className="flex justify-end gap-2 border-t border-line px-5 py-4">
          <Button type="button" variant="ghost" onClick={onClose}>
            Cancel
          </Button>
          <Button type="submit" variant="primary" disabled={submitting}>
            {submitting ? 'Saving…' : isEdit ? 'Save changes' : 'Create'}
          </Button>
        </div>
      </form>
    </div>
  )
}

const inputClass =
  'w-full rounded-md border border-line bg-ink px-3 py-2 font-mono text-sm text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none'
const selectClass = inputClass

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <label className="block">
      <span className="mb-1 block text-xs font-medium text-text-dim">{label}</span>
      {children}
    </label>
  )
}

const kindToneClass: Record<'variable' | 'secret', string> = {
  variable: 'border-variable bg-variable-dim text-variable',
  secret: 'border-secret bg-secret-dim text-secret',
}

function KindOption({
  label,
  tone,
  active,
  onClick,
}: {
  label: string
  tone: 'variable' | 'secret'
  active: boolean
  onClick: () => void
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`flex-1 rounded-md border px-3 py-2 text-sm font-medium transition-colors ${
        active ? kindToneClass[tone] : 'border-line text-text-dim hover:text-text'
      }`}
    >
      {label}
    </button>
  )
}

// client/src/app/features/item-editor/ItemEditorPanel.component.ts
import { AfterViewInit, Component, ElementRef, HostListener, OnInit, ViewChild, computed, inject, input, output, signal } from '@angular/core';
import { CopyFacade } from '../../core/facades/CopyFacade';
import { ItemMutationsFacade } from '../../core/facades/ItemMutationsFacade';
import { SameScope } from '../../core/facades/LedgerSupport';
import { ScopesFacade } from '../../core/facades/ScopesFacade';
import type { PutSecretOptions } from '../../core/gateways/ISecretsGateway';
import type { DashboardScope, GithubEnvironment, ItemKind, ItemLevel, LedgerItem, ScopeRef, SecretVisibility } from '../../core/Types';
import { ButtonComponent } from '../../shared/components/Button.component';

const NAME_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;

interface ReplicateCandidate {
  key: string;
  label: string;
  scope: ScopeRef;
  existing?: LedgerItem;
}

interface ReplicateFailure {
  label: string;
  message: string;
}

/**
 * Port of web/src/features/item-editor/ItemEditorPanel.tsx. All the form fields it seeds from
 * inputs (`level`/`envName`/`kind`/`name`/`value`/`visibility`) are writable signals initialized
 * in ngOnInit rather than field initializers — several depend on required inputs (`scope`), and
 * reading a required input in a field initializer throws NG0950 under `TestBed.createComponent()`
 * + `setInput()` (see RenameEnvironmentDialogComponent's doc comment / core/testing/README.md for
 * the full explanation). Since this component is only ever created fresh (behind an `@if` that
 * flips null -> non-null), ngOnInit running once per open matches the React original's
 * per-mount `useState()` initializers exactly.
 */
@Component({
  selector: 'app-item-editor-panel',
  imports: [ButtonComponent],
  templateUrl: './ItemEditorPanel.component.html',
})
export class ItemEditorPanelComponent implements OnInit, AfterViewInit {
  readonly scope = input.required<DashboardScope>();
  readonly environments = input<GithubEnvironment[]>([]);
  /** The full ledger — used to decide create-vs-update when replicating to other environments. */
  readonly items = input<LedgerItem[]>([]);
  readonly initial = input<LedgerItem | null>(null);
  /** Pre-fill the level/environment when opened from a section's own "+ Add" button. */
  readonly initialLevel = input<ItemLevel | undefined>(undefined);
  readonly initialEnv = input<string | undefined>(undefined);
  /** Pre-fill name/kind when opened to fill in one specific cell (used by CompareView — Phase 8). */
  readonly initialName = input<string | undefined>(undefined);
  readonly initialKind = input<ItemKind | undefined>(undefined);
  /** Locks level/environment/name/kind — used when the target scope+name is already decided for us. */
  readonly lockTarget = input(false);
  readonly showOrgLevel = input.required<boolean>();

  readonly closed = output<void>();

  private readonly itemMutationsFacade = inject(ItemMutationsFacade);
  private readonly copyFacade = inject(CopyFacade);
  private readonly scopesFacade = inject(ScopesFacade);

  @ViewChild('nameInput') private readonly nameInput?: ElementRef<HTMLInputElement>;
  @ViewChild('valueInput') private readonly valueInput?: ElementRef<HTMLTextAreaElement>;

  protected readonly level = signal<ItemLevel>('repository');
  protected readonly envName = signal('');
  protected readonly kind = signal<ItemKind>('variable');
  protected readonly name = signal('');
  protected readonly value = signal('');
  protected readonly visibility = signal<SecretVisibility>('all');
  protected readonly selectedRepoIds = signal<Set<number>>(new Set());
  protected readonly replicateEnvs = signal<Set<string>>(new Set());
  protected readonly error = signal<string | null>(null);
  protected readonly replicateFailures = signal<ReplicateFailure[] | null>(null);

  protected readonly isEdit = computed(() => this.initial() !== null);
  protected readonly isRenaming = computed(() => this.isEdit() && this.name() !== this.initial()!.name);
  protected readonly nameValid = computed(() => this.name().length === 0 || NAME_PATTERN.test(this.name()));
  protected readonly needsVisibilityPicker = computed(() => this.kind() === 'secret' && this.level() === 'organization');

  protected readonly targetScope = computed<ScopeRef>(() => {
    const s = this.scope();
    if (this.level() === 'organization') return { org: s.org };
    if (this.level() === 'repository') return { org: s.org, repo: s.repo };
    return { org: s.org, repo: s.repo, env: this.envName() };
  });

  /** Other environments this new item could also be created in, in one go. */
  protected readonly replicateCandidates = computed<ReplicateCandidate[]>(() => {
    if (this.isEdit() || this.lockTarget() || !this.scope().repo) return [];
    const s = this.scope();
    const kind = this.kind();
    const name = this.name();
    return this.environments()
      .filter((env) => !(this.level() === 'environment' && env.name === this.envName()))
      .map((env) => {
        const envScope: ScopeRef = { org: s.org, repo: s.repo, env: env.name };
        return {
          key: env.name,
          label: env.name,
          scope: envScope,
          existing: this.items().find(
            (i) => i.kind === kind && i.level === 'environment' && i.name === name && SameScope(i.scope, envScope),
          ),
        };
      });
  });

  protected readonly orgReposQuery = this.scopesFacade.OrgReposQuery(
    () => this.scope().org,
    () => this.needsVisibilityPicker() && this.visibility() === 'selected',
  );

  protected readonly submitting = computed(
    () =>
      this.itemMutationsFacade.createVariable.isPending() ||
      this.itemMutationsFacade.updateVariable.isPending() ||
      this.itemMutationsFacade.putSecret.isPending() ||
      this.itemMutationsFacade.renameSecret.isPending() ||
      this.copyFacade.isPending(),
  );

  ngOnInit(): void {
    const initial = this.initial();
    this.level.set(initial?.level ?? this.initialLevel() ?? (this.scope().repo ? 'repository' : 'organization'));
    this.envName.set(initial?.scope.env ?? this.initialEnv() ?? this.environments()[0]?.name ?? '');
    this.kind.set(initial?.kind ?? this.initialKind() ?? 'variable');
    this.name.set(initial?.name ?? this.initialName() ?? '');
    this.value.set(initial?.kind === 'variable' ? (initial.value ?? '') : '');
    this.visibility.set(initial?.visibility ?? 'all');
  }

  ngAfterViewInit(): void {
    if (!this.isEdit() && !this.lockTarget()) this.nameInput?.nativeElement.focus();
    else if (this.isEdit()) this.valueInput?.nativeElement.focus();
  }

  @HostListener('document:keydown', ['$event'])
  protected HandleKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') this.closed.emit();
  }

  protected HandleLevelChange(event: Event): void {
    this.level.set((event.target as HTMLSelectElement).value as ItemLevel);
  }

  protected HandleEnvNameChange(event: Event): void {
    this.envName.set((event.target as HTMLSelectElement).value);
  }

  protected HandleNameInput(event: Event): void {
    this.name.set((event.target as HTMLInputElement).value.toUpperCase());
  }

  protected HandleValueInput(event: Event): void {
    this.value.set((event.target as HTMLTextAreaElement).value);
  }

  protected HandleVisibilityChange(event: Event): void {
    this.visibility.set((event.target as HTMLSelectElement).value as SecretVisibility);
  }

  protected KindOptionClasses(tone: ItemKind): string {
    const active = this.kind() === tone;
    const toneClass = tone === 'variable' ? 'border-variable bg-variable-dim text-variable' : 'border-secret bg-secret-dim text-secret';
    return `flex-1 rounded-md border px-3 py-2 text-sm font-medium transition-colors ${active ? toneClass : 'border-line text-text-dim hover:text-text'}`;
  }

  protected ToggleRepo(id: number): void {
    this.selectedRepoIds.update((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  protected ToggleReplicateEnv(key: string): void {
    this.replicateEnvs.update((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  }

  protected async HandleSubmit(event: Event): Promise<void> {
    event.preventDefault();
    this.error.set(null);
    this.replicateFailures.set(null);

    const name = this.name();
    if (!name.trim() || !NAME_PATTERN.test(name)) {
      this.error.set('Name must start with a letter or underscore and contain only letters, numbers, and underscores.');
      return;
    }
    if (this.level() === 'environment' && !this.envName()) {
      this.error.set('Choose an environment.');
      return;
    }
    const kind = this.kind();
    const value = this.value();
    const isEdit = this.isEdit();
    const isRenaming = this.isRenaming();
    if (kind === 'variable' && !value.trim()) {
      this.error.set('Enter a value for this variable.');
      return;
    }
    if (kind === 'secret' && (!isEdit || isRenaming) && !value) {
      this.error.set(
        isRenaming
          ? 'Enter a value — GitHub can’t copy a secret’s value when renaming it, so you’ll need to re-enter it under the new name.'
          : 'Enter a value for this secret.',
      );
      return;
    }

    const level = this.level();
    const options: PutSecretOptions | undefined =
      kind === 'secret' && level === 'organization'
        ? { visibility: this.visibility(), selectedRepositoryIds: [...this.selectedRepoIds()] }
        : undefined;
    const targetScope = this.targetScope();

    try {
      if (kind === 'variable') {
        if (isEdit) {
          await this.itemMutationsFacade.updateVariable.mutateAsync({
            scope: targetScope,
            level,
            currentName: this.initial()!.name,
            newName: name,
            value,
          });
        } else {
          await this.itemMutationsFacade.createVariable.mutateAsync({ scope: targetScope, level, name, value });
        }
      } else if (isEdit && isRenaming) {
        await this.itemMutationsFacade.renameSecret.mutateAsync({
          scope: targetScope,
          level,
          currentName: this.initial()!.name,
          newName: name,
          value,
          options,
        });
      } else if (isEdit && !value) {
        this.closed.emit();
        return;
      } else {
        await this.itemMutationsFacade.putSecret.mutateAsync({ scope: targetScope, level, name, value, options });
      }

      if (!isEdit && this.replicateEnvs().size > 0) {
        const candidates = this.replicateCandidates();
        const targets = candidates
          .filter((c) => this.replicateEnvs().has(c.key))
          .map((c) => ({ level: 'environment' as const, scope: c.scope, exists: !!c.existing }));
        const outcome = await this.copyFacade.CopyTo(kind, name, value, targets, options);
        if (!outcome.every((r) => r.ok)) {
          this.replicateFailures.set(
            outcome
              .filter((r) => !r.ok)
              .map((r) => ({
                label: candidates.find((c) => SameScope(c.scope, r.target.scope))?.label ?? r.target.scope.env ?? '?',
                message: r.message ?? 'Unknown error',
              })),
          );
          return;
        }
      }

      this.closed.emit();
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : 'GitHub rejected this request.');
    }
  }
}

<div class="fixed inset-0 z-40 flex justify-end bg-black/40 backdrop-blur-[2px]" role="presentation" (click)="closed.emit()">
  <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events -- stopPropagation() only keeps a click inside the panel from bubbling to the backdrop's dismiss handler above; the panel's real controls (inputs/buttons below) are independently keyboard-accessible. -->
  <form
    (submit)="HandleSubmit($event)"
    (click)="$event.stopPropagation()"
    class="flex h-full w-full max-w-md flex-col overflow-y-auto border-l border-line bg-panel shadow-2xl shadow-black/10"
  >
    <div class="border-b border-line px-5 py-4">
      <p class="font-mono text-xs uppercase tracking-widest text-brand">{{ isEdit() ? 'Edit' : 'Add' }}</p>
      <h2 class="mt-1 font-display text-lg font-semibold text-text">
        {{ isEdit() ? initial()!.name : lockTarget() ? initialName() : 'New variable or secret' }}
      </h2>
    </div>

    <div class="flex-1 space-y-4 px-5 py-4">
      <div class="block">
        <span class="mb-1 block text-xs font-medium text-text-dim">Level</span>
        @if (scope().repo && !isEdit() && !lockTarget()) {
          <label class="block">
            <select
              class="w-full rounded-md border border-line bg-ink px-3 py-2 font-mono text-sm text-text focus:border-brand focus:outline-none"
              [value]="level()"
              (change)="HandleLevelChange($event)"
            >
              @if (showOrgLevel()) {
                <option value="organization">Organization ({{ scope().org }})</option>
              }
              <option value="repository">Repository ({{ scope().repo }})</option>
              @if (environments().length > 0) {
                <option value="environment">Environment</option>
              }
            </select>
          </label>
        } @else {
          <p class="font-mono text-sm text-text-dim">{{ level() }}{{ level() === 'environment' ? ': ' + envName() : '' }}</p>
        }
      </div>

      @if (!isEdit() && !lockTarget() && level() === 'environment') {
        <label class="block">
          <span class="mb-1 block text-xs font-medium text-text-dim">Environment</span>
          <select
            class="w-full rounded-md border border-line bg-ink px-3 py-2 font-mono text-sm text-text focus:border-brand focus:outline-none"
            [value]="envName()"
            (change)="HandleEnvNameChange($event)"
          >
            @for (env of environments(); track env.id) {
              <option [value]="env.name">{{ env.name }}</option>
            }
          </select>
        </label>
      }

      <div class="block">
        <span class="mb-1 block text-xs font-medium text-text-dim">Type</span>
        @if (isEdit() || lockTarget()) {
          <p class="font-mono text-sm text-text-dim">{{ kind() }}</p>
        } @else {
          <div class="flex gap-2">
            <button type="button" (click)="kind.set('variable')" [class]="KindOptionClasses('variable')">Variable</button>
            <button type="button" (click)="kind.set('secret')" [class]="KindOptionClasses('secret')">Secret</button>
          </div>
        }
      </div>

      <label class="block">
        <span class="mb-1 block text-xs font-medium text-text-dim">Name</span>
        <input
          #nameInput
          [value]="name()"
          [disabled]="lockTarget()"
          (input)="HandleNameInput($event)"
          placeholder="API_URL"
          spellcheck="false"
          class="w-full rounded-md border border-line bg-ink px-3 py-2 font-mono text-sm text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none"
          [class.opacity-70]="lockTarget()"
        />
        @if (!nameValid()) {
          <p class="mt-1 text-xs text-danger">Letters, numbers, and underscores only.</p>
        }
        @if (isRenaming() && kind() === 'secret') {
          <p class="mt-1 text-xs text-text-dim">
            Secrets can&rsquo;t be renamed directly — this creates
            <span class="font-mono text-secret">{{ name() || '…' }}</span> with the value below, then deletes
            <span class="font-mono">{{ initial()!.name }}</span>.
          </p>
        }
      </label>

      <label class="block">
        <span class="mb-1 block text-xs font-medium text-text-dim">
          {{ kind() === 'secret' ? 'Value (write-only — GitHub will never show it again)' : 'Value' }}
        </span>
        <textarea
          #valueInput
          rows="3"
          [value]="value()"
          (input)="HandleValueInput($event)"
          [placeholder]="isEdit() && kind() === 'secret' ? 'Enter a new value to replace the current one' : ''"
          spellcheck="false"
          class="w-full resize-y rounded-md border border-line bg-ink px-3 py-2 font-mono text-sm text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none"
        ></textarea>
      </label>

      @if (!isEdit() && !lockTarget() && replicateCandidates().length > 0) {
        <div class="block">
          <span class="mb-1 block text-xs font-medium text-text-dim">Also create in other environments</span>
          <div class="max-h-40 space-y-0 overflow-y-auto rounded-md border border-line">
            @for (c of replicateCandidates(); track c.key) {
              <label class="flex items-center gap-2 border-b border-line px-3 py-1.5 text-sm last:border-b-0">
                <input type="checkbox" [checked]="replicateEnvs().has(c.key)" (change)="ToggleReplicateEnv(c.key)" />
                <span class="font-mono text-xs text-text">{{ c.label }}</span>
                @if (c.existing) {
                  <span class="ml-auto text-xs text-danger">will overwrite</span>
                }
              </label>
            }
          </div>
          <p class="mt-1 text-xs text-text-dim">Creates this {{ kind() }} with the same value in every environment checked above.</p>
        </div>
      }

      @if (needsVisibilityPicker()) {
        <label class="block">
          <span class="mb-1 block text-xs font-medium text-text-dim">Which repos can use this?</span>
          <select
            class="w-full rounded-md border border-line bg-ink px-3 py-2 font-mono text-sm text-text focus:border-brand focus:outline-none"
            [value]="visibility()"
            (change)="HandleVisibilityChange($event)"
          >
            <option value="all">All repositories</option>
            <option value="private">Private repositories</option>
            <option value="selected">Selected repositories</option>
          </select>
          @if (visibility() === 'selected') {
            <div class="mt-2 max-h-40 overflow-y-auto rounded-md border border-line">
              @if (orgReposQuery.isLoading()) {
                <p class="p-3 text-xs text-text-dim">Loading repositories&hellip;</p>
              } @else {
                @for (repo of orgReposQuery.data() ?? []; track repo.id) {
                  <label class="flex items-center gap-2 border-b border-line px-3 py-1.5 text-sm text-text last:border-b-0">
                    <input type="checkbox" [checked]="selectedRepoIds().has(repo.id)" (change)="ToggleRepo(repo.id)" />
                    <span class="font-mono text-xs">{{ repo.name }}</span>
                  </label>
                }
              }
            </div>
          }
        </label>
      }

      @if (error()) {
        <p class="text-sm text-danger">{{ error() }}</p>
      }

      @if (replicateFailures(); as failures) {
        <div class="space-y-1 rounded-md border border-danger/30 bg-danger-dim p-2.5">
          <p class="text-xs font-medium text-danger">Saved here, but copying to some environments failed:</p>
          @for (f of failures; track f.label) {
            <p class="text-xs text-text-dim">
              <span class="text-danger">{{ f.label }}</span>: {{ f.message }}
            </p>
          }
        </div>
      }
    </div>

    <div class="flex justify-end gap-2 border-t border-line px-5 py-4">
      <app-button type="button" variant="ghost" (click)="closed.emit()">{{ replicateFailures() ? 'Close' : 'Cancel' }}</app-button>
      <app-button type="submit" variant="primary" [disabled]="submitting()">
        {{ submitting() ? 'Saving…' : isEdit() ? 'Save changes' : 'Create' }}
      </app-button>
    </div>
  </form>
</div>
