// web/src/auth/OAuthDeviceFlow.tsx
import { useEffect, useRef, useState } from 'react'
import { pollDeviceToken, startDeviceFlow, type DeviceCode } from './githubOAuth'
import { Button } from '../components/Button'

type State =
  | { phase: 'idle' }
  | { phase: 'starting' }
  | { phase: 'waiting'; device: DeviceCode; copied: boolean }
  | { phase: 'error'; message: string }

interface OAuthDeviceFlowProps {
  onSuccess: (token: string) => void
}

export function OAuthDeviceFlow({ onSuccess }: OAuthDeviceFlowProps) {
  const [state, setState] = useState<State>({ phase: 'idle' })
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const deadlineRef = useRef<number>(0)
  const cancelledRef = useRef(false)

  useEffect(() => {
    // Reset on (re-)mount — StrictMode's dev-only mount→cleanup→remount cycle would
    // otherwise leave this permanently "cancelled" after the simulated first cleanup.
    cancelledRef.current = false
    return () => {
      cancelledRef.current = true
      if (timerRef.current) clearTimeout(timerRef.current)
    }
  }, [])

  function schedulePoll(device: DeviceCode, intervalSeconds: number) {
    if (timerRef.current) clearTimeout(timerRef.current)
    timerRef.current = setTimeout(() => void poll(device, intervalSeconds), intervalSeconds * 1000)
  }

  async function poll(device: DeviceCode, intervalSeconds: number) {
    if (cancelledRef.current) return

    if (Date.now() > deadlineRef.current) {
      setState({ phase: 'error', message: 'This code expired before it was approved. Try again.' })
      return
    }

    const result = await pollDeviceToken(device.deviceCode)
    if (cancelledRef.current) return

    switch (result.status) {
      case 'success':
        onSuccess(result.token)
        return
      case 'pending':
        schedulePoll(device, intervalSeconds)
        return
      case 'slow_down':
        schedulePoll(device, result.interval)
        return
      case 'denied':
        setState({ phase: 'error', message: 'Sign-in was declined on GitHub. Try again.' })
        return
      case 'expired':
        setState({ phase: 'error', message: 'This code expired. Try again.' })
        return
      case 'error':
        setState({ phase: 'error', message: result.message })
        return
    }
  }

  async function start() {
    setState({ phase: 'starting' })
    try {
      const device = await startDeviceFlow()
      if (cancelledRef.current) return
      deadlineRef.current = Date.now() + device.expiresIn * 1000

      setState({ phase: 'waiting', device, copied: false })
      schedulePoll(device, device.interval)

      // Best-effort — clipboard permission prompts (or their absence) must never block sign-in.
      navigator.clipboard?.writeText(device.userCode).then(
        () => {
          if (!cancelledRef.current) {
            setState((s) => (s.phase === 'waiting' ? { ...s, copied: true } : s))
          }
        },
        () => {
          // clipboard access denied/unavailable — the code is still visible to copy by hand
        },
      )
    } catch (err) {
      if (cancelledRef.current) return
      setState({ phase: 'error', message: err instanceof Error ? err.message : 'Could not start GitHub sign-in.' })
    }
  }

  if (state.phase === 'idle') {
    return (
      <Button variant="primary" className="w-full" onClick={() => void start()}>
        Continue with GitHub
      </Button>
    )
  }

  if (state.phase === 'starting') {
    return <div className="h-9 animate-pulse rounded-md bg-panel-raised" />
  }

  if (state.phase === 'error') {
    return (
      <div className="space-y-3">
        <p className="text-sm text-danger">{state.message}</p>
        <Button variant="primary" className="w-full" onClick={() => void start()}>
          Try again
        </Button>
      </div>
    )
  }

  const { device, copied } = state
  return (
    <div className="space-y-3 text-center">
      <p className="text-xs text-text-dim">Enter this code at GitHub to finish signing in:</p>
      <p className="select-all rounded-md border border-line bg-ink py-3 font-mono text-2xl tracking-[0.3em] text-brand">
        {device.userCode}
      </p>
      {copied ? <p className="text-xs text-text-dim">Copied to your clipboard.</p> : null}
      <a
        href={device.verificationUri}
        target="_blank"
        rel="noreferrer"
        className="inline-flex w-full items-center justify-center rounded-md border border-line bg-panel-raised px-4 py-2 text-sm font-medium text-text hover:border-text-dim"
      >
        Open {device.verificationUri.replace('https://', '')} &rarr;
      </a>
      <p className="font-mono text-xs text-text-dim">
        <span className="mr-1.5 inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-brand align-middle" />
        Waiting for approval&hellip;
      </p>
    </div>
  )
}

// client/src/app/features/auth/OAuthDeviceFlow.component.ts
import { Component, OnDestroy, computed, inject, output, signal } from '@angular/core';
import { ButtonComponent } from '../../shared/components/Button.component';
import { OAUTH_GATEWAY, type DeviceCode, type IOAuthGateway } from '../../core/gateways/IOAuthGateway';

type OAuthDeviceFlowState =
  | { phase: 'idle' }
  | { phase: 'starting' }
  | { phase: 'waiting'; device: DeviceCode; copied: boolean }
  | { phase: 'error'; message: string };

/**
 * Port of web/src/auth/OAuthDeviceFlow.tsx. The original's `cancelledRef`/`timerRef` pattern
 * (plus a "reset on mount" effect specifically to survive React StrictMode's dev-only
 * mount→cleanup→remount cycle) becomes plain instance fields cleaned up in `ngOnDestroy` —
 * Angular doesn't double-invoke lifecycle hooks the way StrictMode does, so there's nothing to
 * work around here.
 */
@Component({
  selector: 'app-oauth-device-flow',
  imports: [ButtonComponent],
  templateUrl: './OAuthDeviceFlow.component.html',
})
export class OAuthDeviceFlowComponent implements OnDestroy {
  private readonly oauthGateway = inject<IOAuthGateway>(OAUTH_GATEWAY);

  readonly success = output<string>();

  protected readonly state = signal<OAuthDeviceFlowState>({ phase: 'idle' });

  protected readonly errorMessage = computed(() => {
    const s = this.state();
    return s.phase === 'error' ? s.message : '';
  });
  protected readonly waitingDevice = computed(() => {
    const s = this.state();
    return s.phase === 'waiting' ? s.device : null;
  });
  protected readonly waitingCopied = computed(() => {
    const s = this.state();
    return s.phase === 'waiting' && s.copied;
  });

  private timer: ReturnType<typeof setTimeout> | null = null;
  private deadline = 0;
  private cancelled = false;

  ngOnDestroy(): void {
    this.cancelled = true;
    if (this.timer) clearTimeout(this.timer);
  }

  protected async Start(): Promise<void> {
    this.state.set({ phase: 'starting' });
    try {
      const device = await this.oauthGateway.StartDeviceFlow();
      if (this.cancelled) return;
      this.deadline = Date.now() + device.expiresIn * 1000;

      this.state.set({ phase: 'waiting', device, copied: false });
      this.SchedulePoll(device, device.interval);

      // Best-effort — clipboard permission prompts (or their absence) must never block sign-in.
      navigator.clipboard?.writeText(device.userCode).then(
        () => {
          if (!this.cancelled) {
            const current = this.state();
            if (current.phase === 'waiting') this.state.set({ ...current, copied: true });
          }
        },
        () => {
          // clipboard access denied/unavailable — the code is still visible to copy by hand
        },
      );
    } catch (err) {
      if (this.cancelled) return;
      this.state.set({
        phase: 'error',
        message: err instanceof Error ? err.message : 'Could not start GitHub sign-in.',
      });
    }
  }

  private SchedulePoll(device: DeviceCode, intervalSeconds: number): void {
    if (this.timer) clearTimeout(this.timer);
    this.timer = setTimeout(() => void this.Poll(device, intervalSeconds), intervalSeconds * 1000);
  }

  private async Poll(device: DeviceCode, intervalSeconds: number): Promise<void> {
    if (this.cancelled) return;

    if (Date.now() > this.deadline) {
      this.state.set({ phase: 'error', message: 'This code expired before it was approved. Try again.' });
      return;
    }

    const result = await this.oauthGateway.PollDeviceToken(device.deviceCode);
    if (this.cancelled) return;

    switch (result.status) {
      case 'success':
        this.success.emit(result.token);
        return;
      case 'pending':
        this.SchedulePoll(device, intervalSeconds);
        return;
      case 'slow_down':
        this.SchedulePoll(device, result.interval);
        return;
      case 'denied':
        this.state.set({ phase: 'error', message: 'Sign-in was declined on GitHub. Try again.' });
        return;
      case 'expired':
        this.state.set({ phase: 'error', message: 'This code expired. Try again.' });
        return;
      case 'error':
        this.state.set({ phase: 'error', message: result.message });
        return;
    }
  }
}

@switch (state().phase) {
  @case ('idle') {
    <app-button variant="primary" extraClass="w-full" (click)="Start()">Continue with GitHub</app-button>
  }
  @case ('starting') {
    <div class="h-9 animate-pulse rounded-md bg-panel-raised"></div>
  }
  @case ('error') {
    <div class="space-y-3">
      <p class="text-sm text-danger">{{ errorMessage() }}</p>
      <app-button variant="primary" extraClass="w-full" (click)="Start()">Try again</app-button>
    </div>
  }
  @case ('waiting') {
    @if (waitingDevice(); as device) {
      <div class="space-y-3 text-center">
        <p class="text-xs text-text-dim">Enter this code at GitHub to finish signing in:</p>
        <p class="select-all rounded-md border border-line bg-ink py-3 font-mono text-2xl tracking-[0.3em] text-brand">
          {{ device.userCode }}
        </p>
        @if (waitingCopied()) {
          <p class="text-xs text-text-dim">Copied to your clipboard.</p>
        }
        <a
          [href]="device.verificationUri"
          target="_blank"
          rel="noreferrer"
          class="inline-flex w-full items-center justify-center rounded-md border border-line bg-panel-raised px-4 py-2 text-sm font-medium text-text hover:border-text-dim"
        >
          Open {{ device.verificationUri.replace('https://', '') }} &rarr;
        </a>
        <p class="font-mono text-xs text-text-dim">
          <span class="mr-1.5 inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-brand align-middle"></span>
          Waiting for approval&hellip;
        </p>
      </div>
    }
  }
}
