// archive/web/src/features/ledger/CopyItemDialog.tsx
import { useMemo, useState, type FormEvent } from 'react'
import { useAuth } from '../../auth/AuthContext'
import { sameScope, useCopyItem, type CopyResult, type DashboardScope } from '../../api/hooks'
import type { GithubEnvironment, ItemLevel, LedgerItem, ScopeRef } from '../../api/types'
import { Button } from '../../components/Button'

interface CopyItemDialogProps {
  item: LedgerItem
  scope: DashboardScope
  environments: GithubEnvironment[]
  showOrgLevel: boolean
  /** The full ledger — used to tell which destinations already have this name (create vs. update, and a same/different-value hint). */
  items: LedgerItem[]
  onClose: () => void
}

interface Candidate {
  key: string
  label: string
  level: ItemLevel
  scope: ScopeRef
  existing?: LedgerItem
}

/** Every other scope in this repo/org that could receive a copy of `source`. */
function buildCandidates(
  source: LedgerItem,
  scope: DashboardScope,
  environments: GithubEnvironment[],
  showOrgLevel: boolean,
  items: LedgerItem[],
): Candidate[] {
  const list: Candidate[] = []
  if (showOrgLevel) {
    list.push({ key: 'organization', label: `Organization · ${scope.org}`, level: 'organization', scope: { org: scope.org } })
  }
  if (scope.repo) {
    list.push({ key: 'repository', label: `Repository · ${scope.repo}`, level: 'repository', scope: { org: scope.org, repo: scope.repo } })
    for (const env of environments) {
      list.push({
        key: `env:${env.name}`,
        label: env.name,
        level: 'environment',
        scope: { org: scope.org, repo: scope.repo, env: env.name },
      })
    }
  }

  return list
    .filter((c) => !(c.level === source.level && sameScope(c.scope, source.scope)))
    .map((c) => ({
      ...c,
      existing: items.find(
        (i) => i.kind === source.kind && i.level === c.level && i.name === source.name && sameScope(i.scope, c.scope),
      ),
    }))
}

export function CopyItemDialog({ item, scope, environments, showOrgLevel, items, onClose }: CopyItemDialogProps) {
  const { token } = useAuth()
  const { copyTo, isPending } = useCopyItem(token)
  const isSecret = item.kind === 'secret'

  const candidates = useMemo(
    () => buildCandidates(item, scope, environments, showOrgLevel, items),
    [item, scope, environments, showOrgLevel, items],
  )

  const [value, setValue] = useState(item.kind === 'variable' ? (item.value ?? '') : '')
  const [selected, setSelected] = useState<Set<string>>(new Set())
  const [error, setError] = useState<string | null>(null)
  const [failures, setFailures] = useState<{ label: string; message: string }[] | null>(null)

  const allSelected = candidates.length > 0 && selected.size === candidates.length

  function toggle(key: string) {
    setSelected((prev) => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })
  }

  function toggleAll() {
    setSelected(allSelected ? new Set() : new Set(candidates.map((c) => c.key)))
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    setError(null)
    setFailures(null)

    if (selected.size === 0) {
      setError('Choose at least one destination.')
      return
    }
    if (isSecret && !value) {
      setError('Enter the value to push — GitHub never returns a secret’s stored value, so it can’t be read and copied automatically.')
      return
    }

    const targets = candidates
      .filter((c) => selected.has(c.key))
      .map((c) => ({ level: c.level, scope: c.scope, exists: !!c.existing }))

    const outcome = await copyTo(item.kind, item.name, value, targets)
    if (outcome.every((r) => r.ok)) {
      onClose()
      return
    }
    setFailures(
      outcome
        .filter((r) => !r.ok)
        .map((r) => ({ label: labelFor(candidates, r), message: r.message ?? 'Unknown error' })),
    )
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4 backdrop-blur-[2px]"
      role="presentation"
      onClick={onClose}
    >
      <form
        onSubmit={handleSubmit}
        onClick={(e) => e.stopPropagation()}
        className="flex max-h-[85vh] w-full max-w-md flex-col overflow-hidden rounded-xl border border-line bg-panel shadow-2xl shadow-black/10"
      >
        <div className="border-b border-line px-5 py-4">
          <p className="font-mono text-xs uppercase tracking-widest text-brand">Copy</p>
          <h2 className="mt-1 font-display text-lg font-semibold text-text">{item.name}</h2>
        </div>

        <div className="flex-1 space-y-4 overflow-y-auto px-5 py-4">
          <label className="block">
            <span className="mb-1 block text-xs font-medium text-text-dim">
              {isSecret ? 'Value to push (write-only — can’t be read back from GitHub)' : 'Value'}
            </span>
            <textarea
              autoFocus
              rows={3}
              value={value}
              onChange={(e) => setValue(e.target.value)}
              spellCheck={false}
              placeholder={isSecret ? 'Enter the value to copy to the scopes below' : ''}
              className="w-full resize-y rounded-md border border-line bg-ink px-3 py-2 font-mono text-sm text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none"
            />
          </label>

          <div>
            <div className="mb-1.5 flex items-center justify-between">
              <span className="text-xs font-medium text-text-dim">Copy to</span>
              {candidates.length > 0 ? (
                <button type="button" onClick={toggleAll} className="text-xs text-brand hover:underline">
                  {allSelected ? 'Clear all' : 'Select all'}
                </button>
              ) : null}
            </div>
            {candidates.length === 0 ? (
              <p className="text-xs text-text-dim">No other scopes available to copy into.</p>
            ) : (
              <div className="max-h-52 space-y-0 overflow-y-auto rounded-md border border-line">
                {candidates.map((c) => (
                  <label
                    key={c.key}
                    className="flex items-center justify-between gap-2 border-b border-line px-3 py-2 text-sm last:border-b-0"
                  >
                    <span className="flex min-w-0 items-center gap-2">
                      <input type="checkbox" checked={selected.has(c.key)} onChange={() => toggle(c.key)} />
                      <span className="truncate text-text">{c.label}</span>
                    </span>
                    {!c.existing ? (
                      <span className="shrink-0 text-xs text-text-dim">not set</span>
                    ) : isSecret ? (
                      <span className="shrink-0 text-xs text-text-dim">already set</span>
                    ) : c.existing.value === value ? (
                      <span className="shrink-0 text-xs text-ok">already matches</span>
                    ) : (
                      <span className="shrink-0 text-xs text-danger">will overwrite</span>
                    )}
                  </label>
                ))}
              </div>
            )}
          </div>

          {error ? <p className="text-sm text-danger">{error}</p> : null}

          {failures ? (
            <div className="space-y-1 rounded-md border border-danger/30 bg-danger-dim p-2.5">
              <p className="text-xs font-medium text-danger">
                Copied to {selected.size - failures.length} of {selected.size} — these failed:
              </p>
              {failures.map((f) => (
                <p key={f.label} className="text-xs text-text-dim">
                  <span className="text-danger">{f.label}</span>: {f.message}
                </p>
              ))}
            </div>
          ) : null}
        </div>

        <div className="flex justify-end gap-2 border-t border-line px-5 py-4">
          <Button type="button" variant="ghost" onClick={onClose}>
            {failures ? 'Close' : 'Cancel'}
          </Button>
          <Button type="submit" variant="primary" disabled={isPending || candidates.length === 0}>
            {isPending ? 'Copying…' : selected.size > 0 ? `Copy to ${selected.size} ${selected.size === 1 ? 'scope' : 'scopes'}` : 'Copy'}
          </Button>
        </div>
      </form>
    </div>
  )
}

function labelFor(candidates: Candidate[], result: CopyResult): string {
  const match = candidates.find((c) => c.level === result.target.level && sameScope(c.scope, result.target.scope))
  return match?.label ?? result.target.level
}

// client/src/app/features/ledger/CopyItemDialog.component.ts
import { AfterViewInit, Component, ElementRef, HostListener, OnInit, ViewChild, computed, inject, input, output, signal } from '@angular/core';
import { CopyFacade } from '../../core/facades/CopyFacade';
import type { CopyResult } from '../../core/facades/CopySupport';
import { SameScope } from '../../core/facades/LedgerSupport';
import type { DashboardScope, GithubEnvironment, ItemLevel, LedgerItem, ScopeRef } from '../../core/Types';
import { ButtonComponent } from '../../shared/components/Button.component';

interface Candidate {
  key: string;
  label: string;
  level: ItemLevel;
  scope: ScopeRef;
  existing?: LedgerItem;
}

interface CopyFailure {
  label: string;
  message: string;
}

/** Every other scope in this repo/org that could receive a copy of `source`. */
function BuildCandidates(
  source: LedgerItem,
  scope: DashboardScope,
  environments: GithubEnvironment[],
  showOrgLevel: boolean,
  items: LedgerItem[],
): Candidate[] {
  const list: Candidate[] = [];
  if (showOrgLevel) {
    list.push({ key: 'organization', label: `Organization · ${scope.org}`, level: 'organization', scope: { org: scope.org } });
  }
  if (scope.repo) {
    list.push({
      key: 'repository',
      label: `Repository · ${scope.repo}`,
      level: 'repository',
      scope: { org: scope.org, repo: scope.repo },
    });
    for (const env of environments) {
      list.push({
        key: `env:${env.name}`,
        label: env.name,
        level: 'environment',
        scope: { org: scope.org, repo: scope.repo, env: env.name },
      });
    }
  }

  return list
    .filter((c) => !(c.level === source.level && SameScope(c.scope, source.scope)))
    .map((c) => ({
      ...c,
      existing: items.find((i) => i.kind === source.kind && i.level === c.level && i.name === source.name && SameScope(i.scope, c.scope)),
    }));
}

function LabelFor(candidates: Candidate[], result: CopyResult): string {
  const match = candidates.find((c) => c.level === result.target.level && SameScope(c.scope, result.target.scope));
  return match?.label ?? result.target.level;
}

/**
 * Port of web/src/features/ledger/CopyItemDialog.tsx. `value` is seeded in ngOnInit rather than a
 * field initializer for the same reason as ItemEditorPanelComponent — see that component's doc
 * comment.
 */
@Component({
  selector: 'app-copy-item-dialog',
  imports: [ButtonComponent],
  templateUrl: './CopyItemDialog.component.html',
})
export class CopyItemDialogComponent implements OnInit, AfterViewInit {
  readonly item = input.required<LedgerItem>();
  readonly scope = input.required<DashboardScope>();
  readonly environments = input<GithubEnvironment[]>([]);
  readonly showOrgLevel = input(false);
  /** The full ledger — used to tell which destinations already have this name (create vs. update, and a same/different-value hint). */
  readonly items = input<LedgerItem[]>([]);

  readonly closed = output<void>();

  private readonly copyFacade = inject(CopyFacade);

  @ViewChild('valueInput') private readonly valueInput?: ElementRef<HTMLTextAreaElement>;

  protected readonly value = signal('');
  protected readonly selected = signal<Set<string>>(new Set());
  protected readonly error = signal<string | null>(null);
  protected readonly failures = signal<CopyFailure[] | null>(null);

  protected readonly isSecret = computed(() => this.item().kind === 'secret');
  protected readonly isPending = this.copyFacade.isPending;

  protected readonly candidates = computed(() =>
    BuildCandidates(this.item(), this.scope(), this.environments(), this.showOrgLevel(), this.items()),
  );
  protected readonly allSelected = computed(
    () => this.candidates().length > 0 && this.selected().size === this.candidates().length,
  );

  ngOnInit(): void {
    const item = this.item();
    this.value.set(item.kind === 'variable' ? (item.value ?? '') : '');
  }

  ngAfterViewInit(): void {
    this.valueInput?.nativeElement.focus();
  }

  @HostListener('document:keydown', ['$event'])
  protected HandleKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') this.closed.emit();
  }

  protected HandleValueInput(event: Event): void {
    this.value.set((event.target as HTMLTextAreaElement).value);
  }

  protected Toggle(key: string): void {
    this.selected.update((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  }

  protected ToggleAll(): void {
    this.selected.set(this.allSelected() ? new Set() : new Set(this.candidates().map((c) => c.key)));
  }

  /** For a variable candidate that already has a value, whether it already matches what's about to be pushed. */
  protected AlreadyMatches(candidate: Candidate): boolean {
    return !this.isSecret() && candidate.existing?.value === this.value();
  }

  protected async HandleSubmit(event: Event): Promise<void> {
    event.preventDefault();
    this.error.set(null);
    this.failures.set(null);

    const selected = this.selected();
    if (selected.size === 0) {
      this.error.set('Choose at least one destination.');
      return;
    }
    const value = this.value();
    if (this.isSecret() && !value) {
      this.error.set(
        'Enter the value to push — GitHub never returns a secret’s stored value, so it can’t be read and copied automatically.',
      );
      return;
    }

    const candidates = this.candidates();
    const targets = candidates
      .filter((c) => selected.has(c.key))
      .map((c) => ({ level: c.level, scope: c.scope, exists: !!c.existing }));

    const item = this.item();
    const outcome = await this.copyFacade.CopyTo(item.kind, item.name, value, targets);
    if (outcome.every((r) => r.ok)) {
      this.closed.emit();
      return;
    }
    this.failures.set(outcome.filter((r) => !r.ok).map((r) => ({ label: LabelFor(candidates, r), message: r.message ?? 'Unknown error' })));
  }
}

<div
  class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4 backdrop-blur-[2px]"
  role="presentation"
  (click)="closed.emit()"
>
  <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events -- stopPropagation() only keeps a click inside the dialog from bubbling to the backdrop's dismiss handler above; the dialog's real controls (inputs/buttons below) are independently keyboard-accessible. -->
  <form
    (submit)="HandleSubmit($event)"
    (click)="$event.stopPropagation()"
    class="flex max-h-[85vh] w-full max-w-md flex-col overflow-hidden rounded-xl border border-line bg-panel shadow-2xl shadow-black/10"
  >
    <div class="border-b border-line px-5 py-4">
      <p class="font-mono text-xs uppercase tracking-widest text-brand">Copy</p>
      <h2 class="mt-1 font-display text-lg font-semibold text-text">{{ item().name }}</h2>
    </div>

    <div class="flex-1 space-y-4 overflow-y-auto px-5 py-4">
      <label class="block">
        <span class="mb-1 block text-xs font-medium text-text-dim">
          {{ isSecret() ? 'Value to push (write-only — can’t be read back from GitHub)' : 'Value' }}
        </span>
        <textarea
          #valueInput
          rows="3"
          [value]="value()"
          (input)="HandleValueInput($event)"
          spellcheck="false"
          [placeholder]="isSecret() ? 'Enter the value to copy to the scopes below' : ''"
          class="w-full resize-y rounded-md border border-line bg-ink px-3 py-2 font-mono text-sm text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none"
        ></textarea>
      </label>

      <div>
        <div class="mb-1.5 flex items-center justify-between">
          <span class="text-xs font-medium text-text-dim">Copy to</span>
          @if (candidates().length > 0) {
            <button type="button" (click)="ToggleAll()" class="text-xs text-brand hover:underline">
              {{ allSelected() ? 'Clear all' : 'Select all' }}
            </button>
          }
        </div>
        @if (candidates().length === 0) {
          <p class="text-xs text-text-dim">No other scopes available to copy into.</p>
        } @else {
          <div class="max-h-52 space-y-0 overflow-y-auto rounded-md border border-line">
            @for (c of candidates(); track c.key) {
              <label class="flex items-center justify-between gap-2 border-b border-line px-3 py-2 text-sm last:border-b-0">
                <span class="flex min-w-0 items-center gap-2">
                  <input type="checkbox" [checked]="selected().has(c.key)" (change)="Toggle(c.key)" />
                  <span class="truncate text-text">{{ c.label }}</span>
                </span>
                @if (!c.existing) {
                  <span class="shrink-0 text-xs text-text-dim">not set</span>
                } @else if (isSecret()) {
                  <span class="shrink-0 text-xs text-text-dim">already set</span>
                } @else if (AlreadyMatches(c)) {
                  <span class="shrink-0 text-xs text-ok">already matches</span>
                } @else {
                  <span class="shrink-0 text-xs text-danger">will overwrite</span>
                }
              </label>
            }
          </div>
        }
      </div>

      @if (error()) {
        <p class="text-sm text-danger">{{ error() }}</p>
      }

      @if (failures(); as fails) {
        <div class="space-y-1 rounded-md border border-danger/30 bg-danger-dim p-2.5">
          <p class="text-xs font-medium text-danger">
            Copied to {{ selected().size - fails.length }} of {{ selected().size }} — these failed:
          </p>
          @for (f of fails; track f.label) {
            <p class="text-xs text-text-dim">
              <span class="text-danger">{{ f.label }}</span>: {{ f.message }}
            </p>
          }
        </div>
      }
    </div>

    <div class="flex justify-end gap-2 border-t border-line px-5 py-4">
      <app-button type="button" variant="ghost" (click)="closed.emit()">{{ failures() ? 'Close' : 'Cancel' }}</app-button>
      <app-button type="submit" variant="primary" [disabled]="isPending() || candidates().length === 0">
        {{
          isPending()
            ? 'Copying…'
            : selected().size > 0
              ? 'Copy to ' + selected().size + ' ' + (selected().size === 1 ? 'scope' : 'scopes')
              : 'Copy'
        }}
      </app-button>
    </div>
  </form>
</div>
