// web/src/features/ledger/Ledger.tsx
import { useMemo, useState } from 'react'
import type { GithubEnvironment, ItemKind, ItemLevel, LedgerItem } from '../../api/types'
import type { LedgerLockedSection, LedgerPartialError } from '../../api/hooks'
import { LedgerRow, LockedRow, ROW_GRID } from './LedgerRow'
import { SectionHeader } from './SectionHeader'
import { FilterBar, type LedgerFilters } from './FilterBar'
import { Button } from '../../components/Button'

interface LedgerProps {
  items: LedgerItem[]
  isLoading: boolean
  error: Error | null
  partialErrors?: LedgerPartialError[]
  lockedSections?: LedgerLockedSection[]
  environments: GithubEnvironment[]
  showRepoLevels: boolean
  showOrgLevel: boolean
  filters: LedgerFilters
  onFiltersChange: (filters: LedgerFilters) => void
  onAdd: () => void
  onAddToSection: (level: ItemLevel, env?: string) => void
  onEdit: (item: LedgerItem) => void
  onDelete: (item: LedgerItem) => void
}

interface Group {
  key: string
  level: ItemLevel
  scopeLabel: string
  description: string
  env?: string
  items: LedgerItem[]
  lockedKinds: ItemKind[]
}

function groupKeyFor(level: ItemLevel, env?: string): string {
  return level === 'environment' ? `env:${env}` : level
}

function descriptionFor(level: ItemLevel, scopeLabel: string, env?: string): string {
  if (level === 'organization') return `Shared with every repo in ${scopeLabel}.`
  if (level === 'repository') return 'Only this repo can use these.'
  return `Only deployments to "${env}" can use these.`
}

function groupItems(items: LedgerItem[], locked: LedgerLockedSection[]): Group[] {
  const groups = new Map<string, Group>()

  function ensureGroup(level: ItemLevel, scopeLabel: string, env?: string): Group {
    const key = groupKeyFor(level, env)
    if (!groups.has(key)) {
      groups.set(key, {
        key,
        level,
        scopeLabel,
        description: descriptionFor(level, scopeLabel, env),
        env,
        items: [],
        lockedKinds: [],
      })
    }
    return groups.get(key)!
  }

  for (const item of items) {
    const scopeLabel = item.level === 'organization' ? item.scope.org : item.level === 'repository' ? item.scope.repo! : item.scope.env!
    ensureGroup(item.level, scopeLabel, item.scope.env).items.push(item)
  }

  for (const l of locked) {
    const g = ensureGroup(l.level, l.scopeLabel, l.env)
    if (!g.lockedKinds.includes(l.kind)) g.lockedKinds.push(l.kind)
  }

  const order: Record<ItemLevel, number> = { organization: 0, repository: 1, environment: 2 }
  return [...groups.values()]
    .map((g) => ({
      ...g,
      items: [...g.items].sort((a, b) =>
        a.kind === b.kind ? a.name.localeCompare(b.name) : a.kind === 'variable' ? -1 : 1,
      ),
    }))
    .sort((a, b) => order[a.level] - order[b.level] || a.scopeLabel.localeCompare(b.scopeLabel))
}

const levelIndent: Record<ItemLevel, string> = {
  organization: 'ml-0',
  repository: 'ml-5',
  environment: 'ml-10',
}

export function Ledger({
  items,
  isLoading,
  error,
  partialErrors = [],
  lockedSections = [],
  environments,
  showRepoLevels,
  showOrgLevel,
  filters,
  onFiltersChange,
  onAdd,
  onAddToSection,
  onEdit,
  onDelete,
}: LedgerProps) {
  const [hideValues, setHideValues] = useState(false)

  const filtered = useMemo(() => {
    return items.filter((item) => {
      if (filters.level !== 'all' && item.level !== filters.level) return false
      if (filters.kind !== 'all' && item.kind !== filters.kind) return false
      if (filters.env !== 'all' && item.scope.env !== filters.env) return false
      if (filters.search && !item.name.toLowerCase().includes(filters.search.toLowerCase())) return false
      return true
    })
  }, [items, filters])

  const filteredLocked = useMemo(() => {
    if (filters.search) return []
    return lockedSections.filter((l) => {
      if (filters.level !== 'all' && l.level !== filters.level) return false
      if (filters.kind !== 'all' && l.kind !== filters.kind) return false
      if (filters.env !== 'all' && l.env !== filters.env) return false
      return true
    })
  }, [lockedSections, filters])

  const groups = useMemo(() => groupItems(filtered, filteredLocked), [filtered, filteredLocked])

  return (
    <div className="flex flex-1 flex-col overflow-hidden rounded-xl border border-line bg-panel shadow-sm shadow-black/[0.03]">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <FilterBar
          filters={filters}
          onChange={onFiltersChange}
          environments={environments}
          showRepoLevels={showRepoLevels}
          showOrgLevel={showOrgLevel}
        />
        <div className="mr-4 flex shrink-0 items-center gap-2">
          <button
            type="button"
            onClick={() => setHideValues((v) => !v)}
            aria-pressed={hideValues}
            title={hideValues ? 'Show variable values' : 'Hide variable values (e.g. before screen-sharing)'}
            className={`flex items-center gap-1.5 rounded-md border px-2.5 py-1.5 font-sans text-xs font-medium transition-colors ${
              hideValues ? 'border-brand bg-brand-dim text-brand' : 'border-line text-text-dim hover:text-text'
            }`}
          >
            {hideValues ? <EyeOffIcon /> : <EyeIcon />}
            {hideValues ? 'Values hidden' : 'Hide values'}
          </button>
          <Button variant="primary" size="sm" onClick={onAdd}>
            + Add
          </Button>
        </div>
      </div>

      {partialErrors.length > 0 ? (
        <div className="border-b border-line bg-danger-dim px-4 py-2">
          <p className="font-sans text-xs font-medium text-danger">
            Couldn&rsquo;t load {partialErrors.length === 1 ? 'one part' : `${partialErrors.length} parts`} of this
            scope
          </p>
          <ul className="mt-1 space-y-0.5">
            {partialErrors.map((e) => (
              <li key={e.label} className="text-xs text-text-dim">
                <span className="text-danger">{e.label}</span>: {e.message}
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      <div className="flex-1 overflow-x-auto overflow-y-auto">
        {isLoading ? (
          <div className="space-y-2 p-4">
            {[0, 1, 2, 3].map((i) => (
              <div key={i} className="h-9 animate-pulse rounded-md bg-panel-raised" />
            ))}
          </div>
        ) : error ? (
          <div className="p-6 text-center">
            <p className="font-display text-sm font-semibold text-danger">Couldn&rsquo;t load this scope</p>
            <p className="mt-2 text-sm text-text-dim">{error.message}</p>
          </div>
        ) : groups.length === 0 ? (
          <div className="p-6 text-center">
            <p className="text-sm text-text-dim">
              {items.length === 0
                ? 'No variables or secrets set here yet — add one to get started.'
                : 'Nothing matches these filters — clear them to see everything in scope.'}
            </p>
          </div>
        ) : (
          <div className="min-w-[46rem]">
            <div
              className={`${ROW_GRID} border-b border-line px-0 py-1.5 font-sans text-[11px] font-medium uppercase tracking-wider text-text-dim`}
            >
              <span />
              <span className="px-3">Type</span>
              <span className="px-1">Name</span>
              <span className="px-3">Value</span>
              <span className="px-3">Access</span>
              <span className="px-3" />
            </div>

            <div className="space-y-5 p-4">
              {groups.map((group) => (
                <div key={group.key} className={levelIndent[group.level]}>
                  <SectionHeader
                    level={group.level}
                    scopeLabel={group.scopeLabel}
                    description={group.description}
                    onAdd={() => onAddToSection(group.level, group.env)}
                  />
                  <div className="mt-1.5 overflow-hidden rounded-lg border border-line">
                    {group.items.map((item) => (
                      <LedgerRow
                        key={item.id}
                        item={item}
                        hideValues={hideValues}
                        onEdit={() => onEdit(item)}
                        onDelete={() => onDelete(item)}
                      />
                    ))}
                    {group.lockedKinds.map((kind) => (
                      <LockedRow key={kind} kind={kind} />
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

function EyeIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="M1 12s4-7 11-7 11 7 11 7-4 7-11 7-11-7-11-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}

function EyeOffIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="M17.94 17.94A10.94 10.94 0 0 1 12 19c-7 0-11-7-11-7a20.6 20.6 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 7 11 7a20.6 20.6 0 0 1-2.16 3.19M14.12 14.12a3 3 0 1 1-4.24-4.24" />
      <path d="M1 1l22 22" />
    </svg>
  )
}

// client/src/app/features/ledger/Ledger.component.ts
import { Component, computed, input, output, signal } from '@angular/core';
import type { LedgerLockedSection, LedgerPartialError } from '../../core/facades/LedgerSupport';
import type { GithubEnvironment, ItemKind, ItemLevel, LedgerItem } from '../../core/Types';
import { ButtonComponent } from '../../shared/components/Button.component';
import { FilterBarComponent } from './FilterBar.component';
import type { LedgerFilters } from './LedgerFilters';
import { LedgerRowComponent, ROW_GRID } from './LedgerRow.component';
import { SectionHeaderComponent } from './SectionHeader.component';

interface Group {
  key: string;
  level: ItemLevel;
  scopeLabel: string;
  description: string;
  env?: string;
  items: LedgerItem[];
  lockedKinds: ItemKind[];
}

const LEVEL_INDENT: Record<ItemLevel, string> = {
  organization: 'ml-0',
  repository: 'ml-5',
  environment: 'ml-10',
};

const LEVEL_ORDER: Record<ItemLevel, number> = { organization: 0, repository: 1, environment: 2 };

function GroupKeyFor(level: ItemLevel, env?: string): string {
  return level === 'environment' ? `env:${env}` : level;
}

function DescriptionFor(level: ItemLevel, scopeLabel: string, env?: string): string {
  if (level === 'organization') return `Shared with every repo in ${scopeLabel}.`;
  if (level === 'repository') return 'Only this repo can use these.';
  return `Only deployments to "${env}" can use these.`;
}

function GroupItems(items: LedgerItem[], locked: LedgerLockedSection[]): Group[] {
  const groups = new Map<string, Group>();

  function EnsureGroup(level: ItemLevel, scopeLabel: string, env?: string): Group {
    const key = GroupKeyFor(level, env);
    let group = groups.get(key);
    if (!group) {
      group = { key, level, scopeLabel, description: DescriptionFor(level, scopeLabel, env), env, items: [], lockedKinds: [] };
      groups.set(key, group);
    }
    return group;
  }

  for (const item of items) {
    const scopeLabel =
      item.level === 'organization' ? item.scope.org : item.level === 'repository' ? item.scope.repo! : item.scope.env!;
    EnsureGroup(item.level, scopeLabel, item.scope.env).items.push(item);
  }

  for (const l of locked) {
    const group = EnsureGroup(l.level, l.scopeLabel, l.env);
    if (!group.lockedKinds.includes(l.kind)) group.lockedKinds.push(l.kind);
  }

  return [...groups.values()]
    .map((g) => ({
      ...g,
      items: [...g.items].sort((a, b) => (a.kind === b.kind ? a.name.localeCompare(b.name) : a.kind === 'variable' ? -1 : 1)),
    }))
    .sort((a, b) => LEVEL_ORDER[a.level] - LEVEL_ORDER[b.level] || a.scopeLabel.localeCompare(b.scopeLabel));
}

/**
 * Port of web/src/features/ledger/Ledger.tsx. Grouping/filtering (GroupItems etc.) stays as free
 * functions in this file rather than moving into a Facade — it's pure presentation shaping of
 * already-fetched data, not a server-cache or business-rule concern, matching where the React
 * original keeps it too. `hideValues` is local UI state (not part of LedgerFilters) for the same
 * reason it is in the original: it's a display toggle, not a filter that changes which items match.
 */
@Component({
  selector: 'app-ledger',
  imports: [FilterBarComponent, ButtonComponent, SectionHeaderComponent, LedgerRowComponent],
  templateUrl: './Ledger.component.html',
})
export class LedgerComponent {
  readonly items = input.required<LedgerItem[]>();
  readonly isLoading = input(false);
  readonly error = input<Error | null>(null);
  readonly partialErrors = input<LedgerPartialError[]>([]);
  readonly lockedSections = input<LedgerLockedSection[]>([]);
  readonly environments = input<GithubEnvironment[]>([]);
  readonly showRepoLevels = input(false);
  readonly showOrgLevel = input(false);
  readonly filters = input.required<LedgerFilters>();

  readonly filtersChange = output<LedgerFilters>();
  readonly add = output<void>();
  readonly addToSection = output<{ level: ItemLevel; env?: string }>();
  readonly editItem = output<LedgerItem>();
  readonly copyItem = output<LedgerItem>();
  readonly deleteItem = output<LedgerItem>();

  protected readonly rowGrid = ROW_GRID;
  protected readonly hideValues = signal(false);

  private readonly filtered = computed(() =>
    this.items().filter((item) => {
      const f = this.filters();
      if (f.level !== 'all' && item.level !== f.level) return false;
      if (f.kind !== 'all' && item.kind !== f.kind) return false;
      if (f.env !== 'all' && item.scope.env !== f.env) return false;
      if (f.search && !item.name.toLowerCase().includes(f.search.toLowerCase())) return false;
      return true;
    }),
  );

  private readonly filteredLocked = computed(() => {
    const f = this.filters();
    if (f.search) return [];
    return this.lockedSections().filter((l) => {
      if (f.level !== 'all' && l.level !== f.level) return false;
      if (f.kind !== 'all' && l.kind !== f.kind) return false;
      if (f.env !== 'all' && l.env !== f.env) return false;
      return true;
    });
  });

  protected readonly groups = computed(() => GroupItems(this.filtered(), this.filteredLocked()));

  protected LevelIndent(level: ItemLevel): string {
    return LEVEL_INDENT[level];
  }

  protected ToggleHideValues(): void {
    this.hideValues.update((v) => !v);
  }
}

<div class="flex flex-1 flex-col overflow-hidden rounded-xl border border-line bg-panel shadow-sm shadow-black/[0.03]">
  <div class="flex flex-wrap items-center justify-between gap-2">
    <app-filter-bar
      [filters]="filters()"
      [environments]="environments()"
      [showRepoLevels]="showRepoLevels()"
      [showOrgLevel]="showOrgLevel()"
      (filtersChange)="filtersChange.emit($event)"
    />
    <div class="mr-4 flex shrink-0 items-center gap-2">
      <button
        type="button"
        (click)="ToggleHideValues()"
        [attr.aria-pressed]="hideValues()"
        [title]="hideValues() ? 'Show variable values' : 'Hide variable values (e.g. before screen-sharing)'"
        class="flex items-center gap-1.5 rounded-md border px-2.5 py-1.5 font-sans text-xs font-medium transition-colors"
        [class.border-brand]="hideValues()"
        [class.bg-brand-dim]="hideValues()"
        [class.text-brand]="hideValues()"
        [class.border-line]="!hideValues()"
        [class.text-text-dim]="!hideValues()"
      >
        @if (hideValues()) {
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
            <path
              d="M17.94 17.94A10.94 10.94 0 0 1 12 19c-7 0-11-7-11-7a20.6 20.6 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 7 11 7a20.6 20.6 0 0 1-2.16 3.19M14.12 14.12a3 3 0 1 1-4.24-4.24"
            />
            <path d="M1 1l22 22" />
          </svg>
        } @else {
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
            <path d="M1 12s4-7 11-7 11 7 11 7-4 7-11 7-11-7-11-7Z" />
            <circle cx="12" cy="12" r="3" />
          </svg>
        }
        {{ hideValues() ? 'Values hidden' : 'Hide values' }}
      </button>
      <app-button variant="primary" size="sm" (click)="add.emit()">+ Add</app-button>
    </div>
  </div>

  @if (partialErrors().length > 0) {
    <div class="border-b border-line bg-danger-dim px-4 py-2">
      <p class="font-sans text-xs font-medium text-danger">
        Couldn&rsquo;t load {{ partialErrors().length === 1 ? 'one part' : partialErrors().length + ' parts' }} of this
        scope
      </p>
      <ul class="mt-1 space-y-0.5">
        @for (e of partialErrors(); track e.label) {
          <li class="text-xs text-text-dim">
            <span class="text-danger">{{ e.label }}</span>: {{ e.message }}
          </li>
        }
      </ul>
    </div>
  }

  <div class="flex-1 overflow-x-auto overflow-y-auto">
    @if (isLoading()) {
      <div class="space-y-2 p-4">
        @for (i of [0, 1, 2, 3]; track i) {
          <div class="h-9 animate-pulse rounded-md bg-panel-raised"></div>
        }
      </div>
    } @else if (error()) {
      <div class="p-6 text-center">
        <p class="font-display text-sm font-semibold text-danger">Couldn&rsquo;t load this scope</p>
        <p class="mt-2 text-sm text-text-dim">{{ error()!.message }}</p>
      </div>
    } @else if (groups().length === 0) {
      <div class="p-6 text-center">
        <p class="text-sm text-text-dim">
          {{
            items().length === 0
              ? 'No variables or secrets set here yet — add one to get started.'
              : 'Nothing matches these filters — clear them to see everything in scope.'
          }}
        </p>
      </div>
    } @else {
      <div class="min-w-[46rem]">
        <div
          class="{{ rowGrid }} border-b border-line px-0 py-1.5 font-sans text-[11px] font-medium uppercase tracking-wider text-text-dim"
        >
          <span></span>
          <span class="px-3">Type</span>
          <span class="px-1">Name</span>
          <span class="px-3">Value</span>
          <span class="px-3">Access</span>
          <span class="px-3"></span>
        </div>

        <div class="space-y-5 p-4">
          @for (group of groups(); track group.key) {
            <div [class]="LevelIndent(group.level)">
              <app-section-header
                [level]="group.level"
                [scopeLabel]="group.scopeLabel"
                [description]="group.description"
                (add)="addToSection.emit({ level: group.level, env: group.env })"
              />
              <div class="mt-1.5 overflow-hidden rounded-lg border border-line">
                @for (item of group.items; track item.id) {
                  <app-ledger-row
                    [item]="item"
                    [hideValues]="hideValues()"
                    (editItem)="editItem.emit(item)"
                    (copyItem)="copyItem.emit(item)"
                    (deleteItem)="deleteItem.emit(item)"
                  />
                }
                @for (kind of group.lockedKinds; track kind) {
                  <div class="{{ rowGrid }} border-b border-line last:border-b-0">
                    <span class="h-full min-h-[2.75rem] bg-line" aria-hidden="true"></span>
                    <span class="px-3 py-2.5 font-mono text-[10px] font-semibold tracking-wide text-text-dim">
                      {{ kind === 'secret' ? 'SEC' : 'VAR' }}
                    </span>
                    <span class="col-span-3 flex items-center gap-1.5 px-1 py-2.5 text-sm text-text-dim">
                      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                        <rect x="3" y="11" width="18" height="10" rx="2" />
                        <path d="M7 11V7a5 5 0 0 1 10 0v4" />
                      </svg>
                      No access to view {{ kind === 'secret' ? 'secrets' : 'variables' }} at this level.
                    </span>
                  </div>
                }
              </div>
            </div>
          }
        </div>
      </div>
    }
  </div>
</div>
