// client/src/app/features/ledger/FilterBar.component.ts
import { Component, computed, input, output } from '@angular/core';
import type { GithubEnvironment, ItemKind } from '../../core/Types';
import type { LedgerFilters } from './LedgerFilters';

interface PillOption<T extends string> {
  value: T;
  label: string;
}

const KIND_OPTIONS: PillOption<ItemKind | 'all'>[] = [
  { value: 'all', label: 'All types' },
  { value: 'variable', label: 'Variables' },
  { value: 'secret', label: 'Secrets' },
];

/**
 * Port of web/src/features/ledger/FilterBar.tsx (the type/const half already lives in
 * LedgerFilters.ts — see that file's doc comment for why it was split out ahead of this
 * component). The React original's generic `Pills<T>` sub-component isn't ported 1:1 — with only
 * two call sites and no reuse beyond this file, a generic component would be unjustified
 * complexity (see docs/CodingStandards.md's "patterns must justify themselves" rule); both pill
 * groups are inlined in the template instead, sharing `PillClasses()`.
 */
@Component({
  selector: 'app-filter-bar',
  templateUrl: './FilterBar.component.html',
})
export class FilterBarComponent {
  readonly filters = input.required<LedgerFilters>();
  readonly environments = input<GithubEnvironment[]>([]);
  readonly showRepoLevels = input(false);
  readonly showOrgLevel = input(false);

  readonly filtersChange = output<LedgerFilters>();

  protected readonly kindOptions = KIND_OPTIONS;

  protected readonly levelOptions = computed<PillOption<LedgerFilters['level']>[]>(() => [
    { value: 'all', label: 'All levels' },
    ...(this.showOrgLevel() ? [{ value: 'organization' as const, label: 'Organization' }] : []),
    ...(this.showRepoLevels()
      ? [
          { value: 'repository' as const, label: 'Repository' },
          { value: 'environment' as const, label: 'Environment' },
        ]
      : []),
  ]);

  protected PillClasses(active: boolean): string {
    return `rounded px-2.5 py-1 font-sans text-xs font-medium transition-colors ${
      active ? 'bg-brand-dim text-brand' : 'text-text-dim hover:text-text'
    }`;
  }

  protected SetLevel(level: LedgerFilters['level']): void {
    this.filtersChange.emit({ ...this.filters(), level });
  }

  protected SetKind(kind: LedgerFilters['kind']): void {
    this.filtersChange.emit({ ...this.filters(), kind });
  }

  protected HandleEnvChange(event: Event): void {
    this.filtersChange.emit({ ...this.filters(), env: (event.target as HTMLSelectElement).value });
  }

  protected HandleSearchInput(event: Event): void {
    this.filtersChange.emit({ ...this.filters(), search: (event.target as HTMLInputElement).value });
  }
}

<div class="flex flex-wrap items-center gap-2 border-b border-line px-4 py-3">
  <div class="flex items-center gap-0.5 rounded-md border border-line bg-ink p-0.5">
    @for (opt of levelOptions(); track opt.value) {
      <button
        type="button"
        (click)="SetLevel(opt.value)"
        [attr.aria-pressed]="filters().level === opt.value"
        [class]="PillClasses(filters().level === opt.value)"
      >
        {{ opt.label }}
      </button>
    }
  </div>

  <div class="flex items-center gap-0.5 rounded-md border border-line bg-ink p-0.5">
    @for (opt of kindOptions; track opt.value) {
      <button
        type="button"
        (click)="SetKind(opt.value)"
        [attr.aria-pressed]="filters().kind === opt.value"
        [class]="PillClasses(filters().kind === opt.value)"
      >
        {{ opt.label }}
      </button>
    }
  </div>

  @if (showRepoLevels() && environments().length > 0) {
    <select
      class="rounded-md border border-line bg-ink px-2.5 py-1.5 font-sans text-xs text-text-dim focus:border-brand focus:text-text focus:outline-none"
      [value]="filters().env"
      (change)="HandleEnvChange($event)"
    >
      <option value="all">All environments</option>
      @for (env of environments(); track env.id) {
        <option [value]="env.name">{{ env.name }}</option>
      }
    </select>
  }

  <input
    [value]="filters().search"
    (input)="HandleSearchInput($event)"
    placeholder="Filter by name&hellip;"
    class="ml-auto min-w-[10rem] rounded-md border border-line bg-ink px-2.5 py-1.5 font-mono text-xs text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none"
  />
</div>

// web/src/features/ledger/FilterBar.tsx
import type { GithubEnvironment, ItemKind, ItemLevel } from '../../api/types'

export interface LedgerFilters {
  level: ItemLevel | 'all'
  kind: ItemKind | 'all'
  env: string | 'all'
  search: string
}

export const defaultFilters: LedgerFilters = { level: 'all', kind: 'all', env: 'all', search: '' }

interface FilterBarProps {
  filters: LedgerFilters
  onChange: (filters: LedgerFilters) => void
  environments: GithubEnvironment[]
  showRepoLevels: boolean
  showOrgLevel: boolean
}

export function FilterBar({ filters, onChange, environments, showRepoLevels, showOrgLevel }: FilterBarProps) {
  const levelOptions: { value: LedgerFilters['level']; label: string }[] = [
    { value: 'all', label: 'All levels' },
    ...(showOrgLevel ? [{ value: 'organization' as const, label: 'Organization' }] : []),
    ...(showRepoLevels ? [{ value: 'repository' as const, label: 'Repository' }] : []),
    ...(showRepoLevels ? [{ value: 'environment' as const, label: 'Environment' }] : []),
  ]

  const kindOptions: { value: LedgerFilters['kind']; label: string }[] = [
    { value: 'all', label: 'All types' },
    { value: 'variable', label: 'Variables' },
    { value: 'secret', label: 'Secrets' },
  ]

  return (
    <div className="flex flex-wrap items-center gap-2 border-b border-line px-4 py-3">
      <Pills value={filters.level} options={levelOptions} onChange={(level) => onChange({ ...filters, level })} />
      <Pills value={filters.kind} options={kindOptions} onChange={(kind) => onChange({ ...filters, kind })} />

      {showRepoLevels && environments.length > 0 ? (
        <select
          className="rounded-md border border-line bg-panel px-2.5 py-1.5 font-sans text-xs text-text-dim focus:border-variable focus:text-text focus:outline-none"
          value={filters.env}
          onChange={(e) => onChange({ ...filters, env: e.target.value })}
        >
          <option value="all">All environments</option>
          {environments.map((env) => (
            <option key={env.id} value={env.name}>
              {env.name}
            </option>
          ))}
        </select>
      ) : null}

      <input
        value={filters.search}
        onChange={(e) => onChange({ ...filters, search: e.target.value })}
        placeholder="Filter by name&hellip;"
        className="ml-auto min-w-[10rem] rounded-md border border-line bg-panel px-2.5 py-1.5 font-mono text-xs text-text placeholder:text-text-dim/60 focus:border-variable focus:outline-none"
      />
    </div>
  )
}

function Pills<T extends string>({
  value,
  options,
  onChange,
}: {
  value: T
  options: { value: T; label: string }[]
  onChange: (value: T) => void
}) {
  return (
    <div className="flex items-center gap-0.5 rounded-md border border-line bg-panel p-0.5">
      {options.map((opt) => (
        <button
          key={opt.value}
          type="button"
          onClick={() => onChange(opt.value)}
          aria-pressed={value === opt.value}
          className={`rounded px-2.5 py-1 font-sans text-xs font-medium transition-colors ${
            value === opt.value ? 'bg-panel-raised text-text' : 'text-text-dim hover:text-text'
          }`}
        >
          {opt.label}
        </button>
      ))}
    </div>
  )
}
