// client/src/app/features/scope-picker/ScopePicker.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild, computed, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/AuthService';
import { LastScopeService } from '../../core/services/LastScopeService';
import { ScopesFacade } from '../../core/facades/ScopesFacade';

/**
 * Port of web/src/features/scope-picker/ScopePicker.tsx. The search input is focused
 * programmatically on init rather than via the `autofocus` attribute — same
 * ElementRef-in-`ngAfterViewInit` pattern as ButtonComponent.Focus()/ConfirmDialogComponent;
 * `autofocus` is flagged by @angular-eslint/template/no-autofocus for good reason (it's a real
 * a11y anti-pattern), and this delivers the same "cursor's ready to type" UX without it.
 */
@Component({
  selector: 'app-scope-picker',
  templateUrl: './ScopePicker.component.html',
})
export class ScopePickerComponent implements AfterViewInit {
  protected readonly authService = inject(AuthService);
  private readonly scopesFacade = inject(ScopesFacade);
  private readonly lastScopeService = inject(LastScopeService);
  private readonly router = inject(Router);

  @ViewChild('searchInput') private readonly searchInput?: ElementRef<HTMLInputElement>;

  ngAfterViewInit(): void {
    this.searchInput?.nativeElement.focus();
  }

  protected readonly orgsQuery = this.scopesFacade.MyOrgsQuery();
  protected readonly reposQuery = this.scopesFacade.MyReposQuery();
  protected readonly lastScope = this.lastScopeService.GetLastScope();

  protected readonly query = signal('');

  protected readonly loading = computed(() => this.orgsQuery.isLoading() || this.reposQuery.isLoading());

  protected readonly filteredOrgs = computed(() =>
    (this.orgsQuery.data() ?? []).filter((o) => o.login.toLowerCase().includes(this.query().toLowerCase())),
  );
  protected readonly filteredRepos = computed(() =>
    (this.reposQuery.data() ?? []).filter((r) => r.fullName.toLowerCase().includes(this.query().toLowerCase())),
  );

  protected HandleQueryInput(event: Event): void {
    this.query.set((event.target as HTMLInputElement).value);
  }

  protected GoToLastScope(): void {
    if (this.lastScope) void this.router.navigateByUrl(this.lastScope.path);
  }

  protected GoToOrg(login: string): void {
    void this.router.navigate(['/o', login]);
  }

  protected GoToRepo(owner: string, name: string): void {
    void this.router.navigate(['/r', owner, name]);
  }
}

<div class="min-h-screen bg-ink">
  <header class="flex items-center justify-between border-b border-line px-6 py-4">
    <div class="flex items-center gap-3">
      <span
        class="flex h-8 w-8 items-center justify-center rounded-lg bg-brand font-display text-sm font-bold text-on-brand"
      >
        G
      </span>
      <h1 class="font-display text-lg font-semibold text-text">Pick a scope</h1>
    </div>
    <div class="flex items-center gap-3 text-sm text-text-dim">
      @if (authService.viewer(); as viewer) {
        <span>Connected as {{ viewer.login }}</span>
      }
      <button (click)="authService.SignOut()" class="text-secret hover:underline">Disconnect</button>
    </div>
  </header>

  <main class="mx-auto max-w-2xl px-6 py-10">
    @if (lastScope) {
      <button (click)="GoToLastScope()" class="mb-4 inline-flex items-center gap-1.5 text-sm text-brand hover:underline">
        &larr; Back to {{ lastScope.label }}
      </button>
    }

    <input
      #searchInput
      [value]="query()"
      (input)="HandleQueryInput($event)"
      placeholder="Search organizations and repositories&hellip;"
      class="w-full rounded-md border border-line bg-panel px-3 py-2 font-mono text-sm text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none"
    />

    @if (loading()) {
      <div class="mt-6 space-y-2">
        @for (i of [0, 1, 2]; track i) {
          <div class="h-11 animate-pulse rounded-md bg-panel"></div>
        }
      </div>
    } @else {
      <div class="mt-6 space-y-6">
        <section>
          <p class="font-display text-xs font-semibold uppercase tracking-wider text-text-dim">Organizations</p>
          <p class="mb-2 mt-0.5 text-xs text-text-dim">Shows every variable and secret shared org-wide.</p>
          @if (filteredOrgs().length > 0) {
            <div class="overflow-hidden rounded-lg border border-line">
              @for (org of filteredOrgs(); track org.login) {
                <button
                  (click)="GoToOrg(org.login)"
                  class="group flex w-full items-center justify-between border-b border-line bg-panel px-4 py-3 text-left last:border-b-0 hover:bg-panel-raised"
                >
                  <span class="truncate font-mono text-sm text-text">{{ org.login }}</span>
                  <span class="flex shrink-0 items-center gap-3">
                    <span class="text-text-dim transition-colors group-hover:text-brand">&rarr;</span>
                  </span>
                </button>
              }
            </div>
          } @else {
            <p class="text-sm text-text-dim">No organizations matched.</p>
          }
        </section>

        <section>
          <p class="font-display text-xs font-semibold uppercase tracking-wider text-text-dim">Repositories</p>
          <p class="mb-2 mt-0.5 text-xs text-text-dim">
            Shows this repo&rsquo;s own variables/secrets, plus its organization&rsquo;s and every deployment
            environment&rsquo;s.
          </p>
          @if (filteredRepos().length > 0) {
            <div class="overflow-hidden rounded-lg border border-line">
              @for (repo of filteredRepos(); track repo.fullName) {
                <button
                  (click)="GoToRepo(repo.owner, repo.name)"
                  class="group flex w-full items-center justify-between border-b border-line bg-panel px-4 py-3 text-left last:border-b-0 hover:bg-panel-raised"
                >
                  <span class="truncate font-mono text-sm text-text">{{ repo.fullName }}</span>
                  <span class="flex shrink-0 items-center gap-3">
                    <span class="text-xs text-text-dim">{{ repo.private ? 'private' : 'public' }}</span>
                    <span class="text-text-dim transition-colors group-hover:text-brand">&rarr;</span>
                  </span>
                </button>
              }
            </div>
          } @else {
            <p class="text-sm text-text-dim">No repositories matched.</p>
          }
        </section>
      </div>
    }
  </main>
</div>

// web/src/features/scope-picker/ScopePicker.tsx
import { useMemo, useState, type ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../auth/AuthContext'
import { useMyOrgs, useMyRepos } from '../../api/hooks'

export function ScopePicker() {
  const { viewer, disconnect } = useAuth()
  const { token } = useAuth()
  const orgsQuery = useMyOrgs(token)
  const reposQuery = useMyRepos(token)
  const [query, setQuery] = useState('')
  const navigate = useNavigate()

  const orgs = useMemo(
    () => (orgsQuery.data ?? []).filter((o) => o.login.toLowerCase().includes(query.toLowerCase())),
    [orgsQuery.data, query],
  )
  const repos = useMemo(
    () => (reposQuery.data ?? []).filter((r) => r.fullName.toLowerCase().includes(query.toLowerCase())),
    [reposQuery.data, query],
  )

  const loading = orgsQuery.isLoading || reposQuery.isLoading

  return (
    <div className="min-h-screen bg-ink">
      <header className="flex items-center justify-between border-b border-line px-6 py-4">
        <div className="flex items-center gap-3">
          <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand font-display text-sm font-bold text-on-brand">
            G
          </span>
          <h1 className="font-display text-lg font-semibold text-text">Pick a scope</h1>
        </div>
        <div className="flex items-center gap-3 text-sm text-text-dim">
          {viewer ? <span>Connected as {viewer.login}</span> : null}
          <button onClick={disconnect} className="text-secret hover:underline">
            Disconnect
          </button>
        </div>
      </header>

      <main className="mx-auto max-w-2xl px-6 py-10">
        <input
          autoFocus
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search organizations and repositories&hellip;"
          className="w-full rounded-md border border-line bg-panel px-3 py-2 font-mono text-sm text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none"
        />

        {loading ? (
          <div className="mt-6 space-y-2">
            {[0, 1, 2].map((i) => (
              <div key={i} className="h-11 animate-pulse rounded-md bg-panel" />
            ))}
          </div>
        ) : (
          <div className="mt-6 space-y-6">
            <Section
              title="Organizations"
              helper="Shows every variable and secret shared org-wide."
              empty="No organizations matched."
            >
              {orgs.map((org) => (
                <Row key={org.login} label={org.login} onClick={() => navigate(`/o/${org.login}`)} />
              ))}
            </Section>

            <Section
              title="Repositories"
              helper="Shows this repo's own variables/secrets, plus its organization's and every deployment environment's."
              empty="No repositories matched."
            >
              {repos.map((repo) => (
                <Row
                  key={repo.fullName}
                  label={repo.fullName}
                  meta={repo.private ? 'private' : 'public'}
                  onClick={() => navigate(`/r/${repo.owner}/${repo.name}`)}
                />
              ))}
            </Section>
          </div>
        )}
      </main>
    </div>
  )
}

function Section({
  title,
  helper,
  empty,
  children,
}: {
  title: string
  helper: string
  empty: string
  children: ReactNode
}) {
  const hasChildren = Array.isArray(children) ? children.length > 0 : !!children
  return (
    <section>
      <p className="font-display text-xs font-semibold uppercase tracking-wider text-text-dim">{title}</p>
      <p className="mb-2 mt-0.5 text-xs text-text-dim">{helper}</p>
      {hasChildren ? (
        <div className="overflow-hidden rounded-lg border border-line">{children}</div>
      ) : (
        <p className="text-sm text-text-dim">{empty}</p>
      )}
    </section>
  )
}

function Row({ label, meta, onClick }: { label: string; meta?: string; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      className="group flex w-full items-center justify-between border-b border-line bg-panel px-4 py-3 text-left last:border-b-0 hover:bg-panel-raised"
    >
      <span className="truncate font-mono text-sm text-text">{label}</span>
      <span className="flex shrink-0 items-center gap-3">
        {meta ? <span className="text-xs text-text-dim">{meta}</span> : null}
        <span className="text-text-dim transition-colors group-hover:text-brand">&rarr;</span>
      </span>
    </button>
  )
}
