// client/src/app/features/auth/ConnectScreen.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/AuthService';
import { OAUTH_GATEWAY, type IOAuthGateway } from '../../core/gateways/IOAuthGateway';
import { ButtonComponent } from '../../shared/components/Button.component';
import { OAuthDeviceFlowComponent } from './OAuthDeviceFlow.component';

type ConnectTab = 'pat' | 'oauth';

/** Port of web/src/auth/ConnectScreen.tsx. */
@Component({
  selector: 'app-connect-screen',
  imports: [ButtonComponent, OAuthDeviceFlowComponent],
  templateUrl: './ConnectScreen.component.html',
})
export class ConnectScreenComponent implements OnInit {
  private readonly authService = inject(AuthService);
  private readonly oauthGateway = inject<IOAuthGateway>(OAUTH_GATEWAY);
  private readonly router = inject(Router);

  protected readonly tab = signal<ConnectTab>('pat');
  protected readonly tokenInput = signal('');
  protected readonly error = signal<string | null>(null);
  protected readonly connecting = signal(false);
  protected readonly oauthClientId = signal<string | null | 'loading'>('loading');

  async ngOnInit(): Promise<void> {
    try {
      this.oauthClientId.set(await this.oauthGateway.FetchOAuthClientId());
    } catch {
      this.oauthClientId.set(null);
    }
  }

  protected TabButtonClasses(active: boolean): string {
    return `flex-1 border-b-2 px-4 py-3 text-sm font-medium transition-colors ${
      active ? 'border-brand text-text' : 'border-transparent text-text-dim hover:text-text'
    }`;
  }

  protected HandleTokenInput(event: Event): void {
    this.tokenInput.set((event.target as HTMLInputElement).value);
  }

  protected async HandlePatSubmit(event: Event): Promise<void> {
    event.preventDefault();
    if (!this.tokenInput().trim()) return;
    this.connecting.set(true);
    this.error.set(null);
    try {
      await this.authService.ConnectWithToken(this.tokenInput().trim(), 'pat');
      await this.router.navigate(['/'], { replaceUrl: true });
    } catch {
      this.error.set(
        'GitHub rejected this token — check that it hasn’t expired and that it carries repo and admin:org scopes.',
      );
    } finally {
      this.connecting.set(false);
    }
  }

  protected async HandleOAuthSuccess(token: string): Promise<void> {
    await this.authService.ConnectWithToken(token, 'oauth');
    await this.router.navigate(['/'], { replaceUrl: true });
  }
}

<div class="relative flex min-h-screen items-center justify-center overflow-hidden bg-ink px-4">
  <div class="pointer-events-none absolute inset-0" aria-hidden="true">
    <div
      class="absolute left-1/2 top-0 h-[40rem] w-[40rem] -translate-x-1/2 -translate-y-1/3 rounded-full bg-brand/10 blur-3xl"
    ></div>
    <div
      class="absolute inset-0"
      style="background-image: radial-gradient(var(--color-line) 1px, transparent 1px); background-size: 26px 26px; mask-image: radial-gradient(ellipse 60% 55% at 50% 35%, black 35%, transparent 100%); -webkit-mask-image: radial-gradient(ellipse 60% 55% at 50% 35%, black 35%, transparent 100%);"
    ></div>
  </div>

  <div class="relative w-full max-w-md">
    <div class="mb-7 text-center">
      <span
        class="mx-auto mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-brand font-display text-base font-bold text-on-brand"
      >
        G
      </span>
      <h1 class="font-display text-3xl font-semibold tracking-tight text-text">Variables Manager</h1>
      <p class="mx-auto mt-2 max-w-sm text-sm text-text-dim">
        One login, every GitHub Actions variable and secret — organization, repository, and environment — in a
        single view.
      </p>
    </div>

    <div class="rounded-xl border border-line bg-panel shadow-xl shadow-black/[0.04]">
      <div class="flex border-b border-line">
        <button type="button" [class]="TabButtonClasses(tab() === 'pat')" (click)="tab.set('pat')">
          Personal access token
        </button>
        <button type="button" [class]="TabButtonClasses(tab() === 'oauth')" (click)="tab.set('oauth')">
          GitHub OAuth
        </button>
      </div>

      @if (tab() === 'pat') {
        <form (submit)="HandlePatSubmit($event)" class="space-y-3 p-5">
          <label for="token-field" class="block text-xs font-medium text-text-dim">Fine-grained or classic token</label>
          <input
            id="token-field"
            type="password"
            autocomplete="off"
            spellcheck="false"
            [value]="tokenInput()"
            (input)="HandleTokenInput($event)"
            placeholder="ghp_..."
            class="w-full rounded-md border border-line bg-ink px-3 py-2 font-mono text-sm text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none"
          />
          <p class="text-xs text-text-dim">
            Needs <code class="text-brand">repo</code> and <code class="text-brand">admin:org</code> scopes to read
            and write variables/secrets at every level. Held only in your browser&rsquo;s local storage &mdash; never
            written to disk.
          </p>
          @if (error()) {
            <p class="text-xs text-danger">{{ error() }}</p>
          }
          <app-button type="submit" variant="primary" extraClass="w-full" [disabled]="connecting() || !tokenInput().trim()">
            {{ connecting() ? 'Connecting…' : 'Connect' }}
          </app-button>
        </form>
      } @else {
        <div class="space-y-3 p-5">
          @if (oauthClientId() === 'loading') {
            <div class="h-9 animate-pulse rounded-md bg-panel-raised"></div>
          } @else if (oauthClientId()) {
            <p class="text-xs text-text-dim">Sign in with your GitHub account &mdash; no token to copy, no secret involved.</p>
            <app-oauth-device-flow (success)="HandleOAuthSuccess($event)" />
          } @else {
            <p class="rounded-md border border-line bg-ink p-3 text-xs text-text-dim">
              OAuth isn&rsquo;t configured on this server yet. Set
              <code class="text-secret">GITHUB_OAUTH_CLIENT_ID</code> in <code>server/.env</code> (from an OAuth App
              with Device Flow enabled), or use a personal access token instead.
            </p>
          }
        </div>
      }
    </div>
  </div>
</div>

// web/src/auth/ConnectScreen.tsx
import { useEffect, useId, useState, type FormEvent, type ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from './AuthContext'
import { fetchOAuthClientId } from './githubOAuth'
import { OAuthDeviceFlow } from './OAuthDeviceFlow'
import { Button } from '../components/Button'

type Tab = 'pat' | 'oauth'

export function ConnectScreen() {
  const [tab, setTab] = useState<Tab>('pat')
  const [tokenInput, setTokenInput] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [connecting, setConnecting] = useState(false)
  const [oauthClientId, setOauthClientId] = useState<string | null | 'loading'>('loading')
  const { connectWithToken } = useAuth()
  const navigate = useNavigate()
  const tokenFieldId = useId()

  useEffect(() => {
    fetchOAuthClientId()
      .then(setOauthClientId)
      .catch(() => setOauthClientId(null))
  }, [])

  async function handlePatSubmit(e: FormEvent) {
    e.preventDefault()
    if (!tokenInput.trim()) return
    setConnecting(true)
    setError(null)
    try {
      await connectWithToken(tokenInput.trim(), 'pat')
      navigate('/', { replace: true })
    } catch {
      setError('GitHub rejected this token — check that it hasn’t expired and that it carries repo and admin:org scopes.')
    } finally {
      setConnecting(false)
    }
  }

  async function handleOAuthSuccess(token: string) {
    await connectWithToken(token, 'oauth')
    navigate('/', { replace: true })
  }

  return (
    <div className="relative flex min-h-screen items-center justify-center overflow-hidden bg-ink px-4">
      <div className="pointer-events-none absolute inset-0" aria-hidden="true">
        <div className="absolute left-1/2 top-0 h-[40rem] w-[40rem] -translate-x-1/2 -translate-y-1/3 rounded-full bg-brand/10 blur-3xl" />
        <div
          className="absolute inset-0"
          style={{
            backgroundImage: 'radial-gradient(var(--color-line) 1px, transparent 1px)',
            backgroundSize: '26px 26px',
            maskImage: 'radial-gradient(ellipse 60% 55% at 50% 35%, black 35%, transparent 100%)',
            WebkitMaskImage: 'radial-gradient(ellipse 60% 55% at 50% 35%, black 35%, transparent 100%)',
          }}
        />
      </div>

      <div className="relative w-full max-w-md">
        <div className="mb-7 text-center">
          <span className="mx-auto mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-brand font-display text-base font-bold text-on-brand">
            G
          </span>
          <h1 className="font-display text-3xl font-semibold tracking-tight text-text">Variables Manager</h1>
          <p className="mx-auto mt-2 max-w-sm text-sm text-text-dim">
            One login, every GitHub Actions variable and secret — organization, repository, and environment — in a
            single view.
          </p>
        </div>

        <div className="rounded-xl border border-line bg-panel shadow-xl shadow-black/[0.04]">
          <div className="flex border-b border-line">
            <TabButton active={tab === 'pat'} onClick={() => setTab('pat')}>
              Personal access token
            </TabButton>
            <TabButton active={tab === 'oauth'} onClick={() => setTab('oauth')}>
              GitHub OAuth
            </TabButton>
          </div>

          {tab === 'pat' ? (
            <form onSubmit={handlePatSubmit} className="space-y-3 p-5">
              <label htmlFor={tokenFieldId} className="block text-xs font-medium text-text-dim">
                Fine-grained or classic token
              </label>
              <input
                id={tokenFieldId}
                type="password"
                autoComplete="off"
                spellCheck={false}
                value={tokenInput}
                onChange={(e) => setTokenInput(e.target.value)}
                placeholder="ghp_..."
                className="w-full rounded-md border border-line bg-ink px-3 py-2 font-mono text-sm text-text placeholder:text-text-dim/60 focus:border-brand focus:outline-none"
              />
              <p className="text-xs text-text-dim">
                Needs <code className="text-brand">repo</code> and <code className="text-brand">admin:org</code>{' '}
                scopes to read and write variables/secrets at every level. Held only in this tab&rsquo;s session storage
                &mdash; never written to disk.
              </p>
              {error ? <p className="text-xs text-danger">{error}</p> : null}
              <Button type="submit" variant="primary" className="w-full" disabled={connecting || !tokenInput.trim()}>
                {connecting ? 'Connecting…' : 'Connect'}
              </Button>
            </form>
          ) : (
            <div className="space-y-3 p-5">
              {oauthClientId === 'loading' ? (
                <div className="h-9 animate-pulse rounded-md bg-panel-raised" />
              ) : oauthClientId ? (
                <>
                  <p className="text-xs text-text-dim">
                    Sign in with your GitHub account &mdash; no token to copy, no secret involved.
                  </p>
                  <OAuthDeviceFlow onSuccess={(token) => void handleOAuthSuccess(token)} />
                </>
              ) : (
                <p className="rounded-md border border-line bg-ink p-3 text-xs text-text-dim">
                  OAuth isn&rsquo;t configured on this server yet. Set{' '}
                  <code className="text-secret">GITHUB_OAUTH_CLIENT_ID</code> in <code>server/.env</code> (from an
                  OAuth App with Device Flow enabled), or use a personal access token instead.
                </p>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

function TabButton({
  active,
  onClick,
  children,
}: {
  active: boolean
  onClick: () => void
  children: ReactNode
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`flex-1 border-b-2 px-4 py-3 text-sm font-medium transition-colors ${
        active ? 'border-brand text-text' : 'border-transparent text-text-dim hover:text-text'
      }`}
    >
      {children}
    </button>
  )
}
