// client/src/app/shared/components/Avatar.component.ts
import { Component, computed, input, signal } from '@angular/core';

/**
 * Port of web/src/components/Avatar.tsx. Shows the account's GitHub profile photo; falls back
 * to (and stays on, while the image loads or if it fails) the first-letter initial.
 */
@Component({
  selector: 'app-avatar',
  templateUrl: './Avatar.component.html',
})
export class AvatarComponent {
  readonly login = input.required<string>();
  readonly avatarUrl = input<string | undefined>(undefined);
  readonly size = input(24);

  protected readonly loaded = signal(false);
  protected readonly errored = signal(false);

  protected readonly initial = computed(() => this.login().trim().charAt(0).toUpperCase() || '?');
  protected readonly showImage = computed(() => Boolean(this.avatarUrl()) && !this.errored());
  protected readonly altText = computed(() => `${this.login()}'s avatar`);
}

<span
  class="relative flex shrink-0 items-center justify-center overflow-hidden rounded-full bg-brand font-display text-xs font-bold text-on-brand"
  [style.width.px]="size()"
  [style.height.px]="size()"
>
  @if (!(showImage() && loaded())) {
    <span [attr.aria-hidden]="showImage()">{{ initial() }}</span>
  }
  @if (showImage()) {
    <img
      [src]="avatarUrl()"
      [alt]="altText()"
      (load)="loaded.set(true)"
      (error)="errored.set(true)"
      class="absolute inset-0 h-full w-full object-cover"
      [class.hidden]="!loaded()"
    />
  }
</span>

// archive/web/src/components/Avatar.tsx
import { useState } from 'react'

interface AvatarProps {
  login: string
  avatarUrl?: string
  size?: number
}

export function Avatar({ login, avatarUrl, size = 24 }: AvatarProps) {
  const [loaded, setLoaded] = useState(false)
  const [errored, setErrored] = useState(false)
  const initial = login.trim().charAt(0).toUpperCase() || '?'
  const showImage = Boolean(avatarUrl) && !errored

  return (
    <span
      className="relative flex shrink-0 items-center justify-center overflow-hidden rounded-full bg-brand font-display text-xs font-bold text-on-brand"
      style={{ width: size, height: size }}
    >
      {!(showImage && loaded) ? <span aria-hidden={showImage}>{initial}</span> : null}
      {showImage ? (
        <img
          src={avatarUrl}
          alt={`${login}'s avatar`}
          onLoad={() => setLoaded(true)}
          onError={() => setErrored(true)}
          className={`absolute inset-0 h-full w-full object-cover ${loaded ? '' : 'hidden'}`}
        />
      ) : null}
    </span>
  )
}
