// client/src/app/shared/components/ConfirmDialog.component.ts
import { AfterViewInit, Component, HostListener, ViewChild, input, output } from '@angular/core';
import { ButtonComponent } from './Button.component';

/**
 * Port of web/src/components/ConfirmDialog.tsx. `description` (typed `ReactNode` in the
 * original — a plain string at most call sites, but a bullet list of affected scopes in
 * CompareView's delete-everywhere flow) becomes projected content via `<ng-content>`: callers
 * put whatever markup they need between this component's open/close tags instead of passing an
 * input.
 */
@Component({
  selector: 'app-confirm-dialog',
  imports: [ButtonComponent],
  templateUrl: './ConfirmDialog.component.html',
})
export class ConfirmDialogComponent implements AfterViewInit {
  readonly title = input.required<string>();
  readonly confirmLabel = input.required<string>();
  readonly error = input<string | null>(null);
  readonly confirming = input(false);

  // Past-tense, not `confirm`/`cancel` — `cancel` specifically collides with a real native DOM
  // event (HTMLDialogElement and <input type="file"> both dispatch one), which
  // @angular-eslint/no-output-native rightly flags as a footgun.
  readonly confirmed = output<void>();
  readonly cancelled = output<void>();

  @ViewChild('confirmButton') private readonly confirmButton?: ButtonComponent;

  ngAfterViewInit(): void {
    this.confirmButton?.Focus();
  }

  @HostListener('document:keydown', ['$event'])
  protected HandleKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') this.cancelled.emit();
  }
}

<div
  class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4 backdrop-blur-[2px]"
  role="presentation"
  (click)="cancelled.emit()"
>
  <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events -- this stopPropagation() only keeps a click inside the dialog from bubbling to the backdrop's dismiss handler above; it isn't itself a user action, and the dialog's real interactive controls (the buttons below) are independently keyboard-accessible. -->
  <div
    role="alertdialog"
    aria-modal="true"
    aria-labelledby="confirm-title"
    class="w-full max-w-sm rounded-xl border border-line bg-ink p-5 shadow-2xl shadow-black/10"
    (click)="$event.stopPropagation()"
  >
    <h2 id="confirm-title" class="font-sans text-base font-semibold text-text">{{ title() }}</h2>
    <div class="mt-2 text-sm text-text-dim">
      <ng-content />
    </div>
    @if (error()) {
      <p class="mt-3 text-sm text-danger">{{ error() }}</p>
    }
    <div class="mt-5 flex justify-end gap-2">
      <app-button variant="ghost" [disabled]="confirming()" (click)="cancelled.emit()">Cancel</app-button>
      <app-button #confirmButton variant="danger" [disabled]="confirming()" (click)="confirmed.emit()">
        {{ confirming() ? 'Deleting…' : confirmLabel() }}
      </app-button>
    </div>
  </div>
</div>

// web/src/components/ConfirmDialog.tsx
import { useEffect, useRef, type ReactNode } from 'react'
import { Button } from './Button'

interface ConfirmDialogProps {
  title: string
  description: ReactNode
  confirmLabel: string
  error?: string | null
  confirming?: boolean
  onConfirm: () => void
  onCancel: () => void
}

export function ConfirmDialog({
  title,
  description,
  confirmLabel,
  error,
  confirming,
  onConfirm,
  onCancel,
}: ConfirmDialogProps) {
  const confirmRef = useRef<HTMLButtonElement>(null)

  useEffect(() => {
    confirmRef.current?.focus()
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onCancel()
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [onCancel])

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4 backdrop-blur-[2px]"
      role="presentation"
      onClick={onCancel}
    >
      <div
        role="alertdialog"
        aria-modal="true"
        aria-labelledby="confirm-title"
        className="w-full max-w-sm rounded-xl border border-line bg-ink p-5 shadow-2xl shadow-black/10"
        onClick={(e) => e.stopPropagation()}
      >
        <h2 id="confirm-title" className="font-sans text-base font-semibold text-text">
          {title}
        </h2>
        <div className="mt-2 text-sm text-text-dim">{description}</div>
        {error ? <p className="mt-3 text-sm text-danger">{error}</p> : null}
        <div className="mt-5 flex justify-end gap-2">
          <Button variant="ghost" onClick={onCancel} disabled={confirming}>
            Cancel
          </Button>
          <Button ref={confirmRef} variant="danger" onClick={onConfirm} disabled={confirming}>
            {confirming ? 'Deleting…' : confirmLabel}
          </Button>
        </div>
      </div>
    </div>
  )
}
