// client/src/app/shared/components/RateLimitIndicator.component.ts
import { Component, computed, inject } from '@angular/core';
import { RateLimitService } from '../../core/services/RateLimitService';

/** Port of web/src/components/RateLimitIndicator.tsx. */
@Component({
  selector: 'app-rate-limit-indicator',
  templateUrl: './RateLimitIndicator.component.html',
})
export class RateLimitIndicatorComponent {
  private readonly rateLimitService = inject(RateLimitService);

  protected readonly rateLimit = this.rateLimitService.state;

  protected readonly low = computed(() => {
    const info = this.rateLimit();
    return info ? info.remaining < info.limit * 0.1 : false;
  });

  protected readonly resetLabel = computed(() => {
    const resetAt = this.rateLimit()?.resetAt;
    return resetAt ? new Date(resetAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : null;
  });

  protected readonly titleText = computed(() => (this.resetLabel() ? `Resets ${this.resetLabel()}` : null));
}

@if (rateLimit(); as info) {
  <span class="font-mono text-xs" [class.text-danger]="low()" [class.text-text-dim]="!low()" [title]="titleText()">
    {{ info.remaining }}/{{ info.limit }} API calls left
  </span>
}

// web/src/components/RateLimitIndicator.tsx
import { useRateLimit } from '../lib/rateLimitStore'

export function RateLimitIndicator() {
  const rateLimit = useRateLimit()
  if (!rateLimit) return null

  const low = rateLimit.remaining < rateLimit.limit * 0.1
  const resetLabel = rateLimit.resetAt
    ? new Date(rateLimit.resetAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    : null

  return (
    <span
      className={`font-mono text-xs ${low ? 'text-danger' : 'text-text-dim'}`}
      title={resetLabel ? `Resets ${resetLabel}` : undefined}
    >
      {rateLimit.remaining}/{rateLimit.limit} API calls left
    </span>
  )
}
